### ISSUE TITLE
Imatge de capçalera configurable per pàgines de categoria i etiqueta

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#1]
_From @jmeler on October 15, 2014 11:17_

Per potenciar els blocs de nivell i d'aula, fer configurable la imatge de capçalera per categories i etiquetes. Imatge o carrusel. 

_Copied from original issue: projectestac/agora#19_

**Comment by sarjona** [comment]
Incorporat a la versió 16.02.01
