### ISSUE TITLE
Editor visual pels ginys

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#10]
_From @jmeler on November 5, 2014 12:38_

Incloure un editor visual pels ginys.

Plugins disponibles: 

-En principi, el plugin més popular és Black studio tinymce widget (https://wordpress.org/plugins/black-studio-tinymce-widget/) però s'ha provat i no funciona bé. S'ha provat a dos entorns (Àgora i entorn extern)

-WYSIWYG Widgets / Widget Blocks. Crea un tipus de post. Potser no calia per implementar una cosa tan simple. Perjudica la usabilitat (edició de ginys en un lloc i edicions de ginys d'aquest tipus en un altre... i més elements a la barra d'administració)

-WP-Editor-Widget (https://wordpress.org/plugins/wp-editor-widget/)
Aquest plugin utilitza bàsicament la funció nativa de wordpress wp-editor per mostrar un editor visual per l'edició de ginys. És bastant net. Funciona correctament. 

_Copied from original issue: projectestac/agora#57_

**Comment by jmeler** [comment]
Relacionada #243

**Comment by sarjona** [comment]
Instal·lar el **Black Studio TinyMCE Widget.** (https://wordpress.org/plugins/black-studio-tinymce-widget/) i revisar els errors que comentava el Xavi als comentaris a la issue https://github.com/projectestac/agora_nodes/issues/243.

**Comment by sarjona** [comment]
@jmeler Tal com hem parlat, cal estudiar si convé instal·lar aquest connector o bé es pot utilitzar la funcionalitat dels **Enllaços**.

**Comment by monicagrau** [comment]
Ens tornen a demanar per aquesta funcionalitat. Quan estigui hauríem d'avisar a la usuària en aquest fil: http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=79946#p358932

**Comment by jmeler** [comment]
WordPress ha incorporat un editor força funcional com a giny de text. Permet incloure negreta, cursiva, llistes i imatges.
