### ISSUE TITLE
BuddyPress: Registre de comentaris esborrats

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#106]
És necessari implementar un mecanisme de registre per desar un comentari a BuddyPress si l'usuari l'esborra. Si un alumne escriu un comentari ofensiu i després l'esborra, no queda cap registre.

**Comment by jmeler** [comment]
Fase1: Descàrrega CSV

**Comment by sarjona** [comment]
Resolt al commit https://github.com/projectestac/agora_nodes/commit/83197f956bece36c01eea9066e3fb120e977d5d2
