### ISSUE TITLE
Revisar permissos del rol col·laborador

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#116]
Verificar si un usuari amb drets de col·laborador pot accedir directament (via url) a les opcions que veu un administrador.

**Comment by jmeler** [comment]
Aquest enllaços són accessibles encara que les opcions estiguin amagades:

https://agora/agora/usu1/wp-admin/edit-comments.php
https://agora/agora/usu1/wp-admin/edit.php?post_type=gce_feed
https://agora/agora/usu1/wp-admin/post-new.php?post_type=gce_feed
https://agora/agora/usu1/wp-admin/tools.php

Revisar totes les pàgines del backend.

**Comment by toniginard** [comment]
Fixed in next release
