### ISSUE TITLE
BuddyPress: Botons associats al perfil d'usuari desapareixen de manera aleatoria

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#117]
![seleccio_999 022](https://cloud.githubusercontent.com/assets/5380649/6617543/f5fc9118-c8b9-11e4-992c-e52943186993.png)

Passa el mateix amb el botó d'acceptar membres dins d'un node privat.

**Comment by jmeler** [comment]
https://buddypress.trac.wordpress.org/ticket/5170

**Comment by jmeler** [comment]
El problema és que hi ha un conflicte entre el core del buddypress i el giny "(BuddyPress) Membres recentment actius". Tot i que hi ha un patch, el ticket segueix obert i desenvolupadors contrastats diuen que pot tenir efectes no desitjats imprevisibles. De moment, la "solució" passa per no fer servir aquest giny. De fet, el giny "(BuddyPress) Members" pot fer la mateixa funció i no provoca cap conflicte.

**Comment by jmeler** [comment]
Bones notícies. Sembla que quedarà solucionat a la propera versió de BuddyPress: https://buddypress.trac.wordpress.org/changeset/10553

**Comment by sarjona** [comment]
S'ha convertit a submòdul el BuddyPress i s'ha actualitzat a la 2.5.3: https://github.com/projectestac/wordpress-buddypress - https://github.com/projectestac/agora_nodes/commit/252ae4a7a02f182b93faa0ab74156e9fff8c0199

Pendent confirmar que la incidència ha quedat resolta després de l'actualització a 2.5.3

**Comment by monicagrau** [comment]
Ja no hem aconseguit reproduir l'error. Sembla que finalment s'ha resolt.
