### ISSUE TITLE
Traducció del bloc de comentaris

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#118]
![seleccio_999 023](https://cloud.githubusercontent.com/assets/5380649/6617552/0ba95fbe-c8ba-11e4-9e26-a065e0c964ea.png)

Revisar també literals quan hi ha comentaris (Reply etc...)

**Comment by sarjona** [comment]
Ahir fent proves d'aquesta part vaig trobar i revisar algun d'aquests literals :-)
