### ISSUE TITLE
BBPress: pujada de fitxers

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#130]
Per poder penjar fitxers directament al fòrum, és necessari activar el paràmetre 

-Fancy editor media upload	 
Enable media upload tab for the fancy editor, only shows for users who can upload files

Això habilita un botó per penjar fitxers però al intentar penjar fitxers, es produeix un error semblant a l'error de BuddyPress. Al pujar fitxers al fòrum (BBPress) genera un error HTTP: disallowed for cross-origin requests that require preflight

Per tant, 2 accions per solucionar aquesta incidència:
-Activació massiva (SQL) d'aquest paràmetre a tots els centres
-Afegir hook similar al de BuddyPress (https per http: https://github.com/projectestac/agora_nodes/commit/c0412bcf5ac08b6b5dbe5159d524fbbbce56d911)

**Comment by sarjona** [comment]
Pendent estudi per confirmar si és viable moure Nodes perquè funcioni amb HTTPS.
