### ISSUE TITLE
Giny RSS: alguns feeds vàlids no es carreguen

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#132]
Per exemple, el feed del Departament d'Ensenyament 

http://ensenyament.gencat.cat/ca/rss/rss-actualitat/

genera aquest error: 

![seleccio_999 069](https://cloud.githubusercontent.com/assets/5380649/7043674/97acf692-ddeb-11e4-92b9-62329eeace43.png)

NOTA: Revisar el codi que es va canviar a xtecblocs per evitar els bucles de peticions RSS.

**Comment by jmeler** [comment]
Revisar el codi que es va canviar a xtecblocs per evitar els bucles de peticions RSS.

**Comment by monicagrau** [comment]
S'ha confirmat que aquest canal RSS funciona tant a altres serveis com Moodle i també a blogs de Wordpress.org i de Blogger.

**Comment by jmeler** [comment]
Aquest RSS ja funciona (tot i que mostra notícies antigues)
