### ISSUE TITLE
Evitar l'esborrament de pàgines estructurals

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#134]
Evitar que l'usuari pugi esborrar les següents pàgines necessaries pel bon funcionament:
-Pàgina d'inici
-Membres
-Activitat
-Nodes

Modificar la plantilla de la portada de manera que si no hi ha cap pàgina d'inici, carregui una pàgina buida o la pàgina d'inici estructural (aquesta que no es pot esborrar).

**Comment by jmeler** [comment]
Afegir una comprobació extra. Si no hi ha definida cap pàgina d'inici, el sistema ha de configurar com a pàgina d'inici, la pàgina d'inici estructural (anomenada pàgina d'inici)

Relacionada:
https://github.com/projectestac/agora_nodes/issues/102

**Comment by jmeler** [comment]
He reoberta la issue perquè ha deixat de funcionar. A més a més, es proposa millores extra.

**Comment by sarjona** [comment]
Resolt al commit: https://github.com/projectestac/agora_nodes/commit/b5336ae6f89cee217d54678a497edc58ae74bf14
