### ISSUE TITLE
Suggerir etiquetes a BP-Docs

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#135]
De manera similar a com el camp "Etiquetes" del formulari d'articles de WordPress, Nodes hauria de sugerir etiquetes existents en el moment d'introduir etiquetes al formulari del BP-Docs.

És una millora CLAU per aconseguir coherència al gestor documental de Nodes. És molt desmotivador per a l'usuari gestor de documents trovar-se que ha introduit etiquetes redundants, molt semblants però no iguals. Ex: actes, acta; sortida, sortides; 

NOTA: Revisar si la darrera versió de BP-Docs inclou aquesta nova característica (fan actualitzacions sovint)

**Comment by sarjona** [comment]
La versió actual (1.8.8) ja està instal·lada a Àgora-Nodes i encara no admet aquesta funcionalitat.

**Comment by monicagrau** [comment]
Al fòrum de Nodes ens han fet arribar altres suggeriments a tenir en compte relacionats amb aquest tema: http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=83926

**Comment by sarjona** [comment]
Implementat al PR https://github.com/projectestac/agora_nodes/pull/425 i https://github.com/projectestac/wordpress-buddypress-docs/pull/4
