### ISSUE TITLE
Vista Subpàgines: Pàgina mare visitable

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#150]
El menú de pàgines té un comportament una mica desconcertant. 

Quan fas clic sobre una pàgina mare, es desplega un menú amb les pàgines filles. Però no mostra la pàgina mare. La pàgina mare queda en un "limbo" i no és pot visitar (només via fil d'ariadna o url directament). 

S'hauria de modificar el comportament:
- Al fer clic sobre la pàgina mare, anem a la pàgina mare. al fer clic fora de l'enllaç de la pàgina mare però dins del div, es desplega l'acordeó amb les subpàgines. 
- Al visitar una pàgina "mare", mostrar desplegat l'accordéo amb grup de subpàgines.

**Comment by sarjona** [comment]
Resolta a la versió 15.12.14
