### ISSUE TITLE
Afegir enllaços de twitter, facebook, google+ als articles i pàgines

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#160]
Revisar si **addthis** és el plugin més adequat (o simplificar la seva configuració): 
- El botons s'han de mostrar al mode article complet, no a les targetes resum de les pàgines de categoria. 
- Si algun usuari vol promocionar un article o pàgina ha d'entrar a l'article o pàgina.

**Comment by monicagrau** [comment]
Un bon candidat podria ser aquest: https://en.support.wordpress.com/sharing/

**Comment by ignacioabejaro** [comment]
Aquest pot ser un bon candidat https://wordpress.org/plugins/add-to-any/

**Comment by jmeler** [comment]
Molt bona pinta, nacho, fàcil i amb les funcionalitats juestes. No requereix validació. M'agrada, per mi endavant.

**Comment by jmeler** [comment]
Tanco, oberta la https://github.com/projectestac/agora_nodes/issues/267
