### ISSUE TITLE
Traduccions

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#184]
- "Llegir més" per "Llegeix més" quan es tria el separador a l'editor

- Canviar el text a sota del resum (edició d'articles):

>Els Resums, són textos breus opcionals del contingut escrits manualment que podeu usar al tema. Apreneu més sobre els resums manuals (en anglès).

per aquest text:

>Si no definiu cap resum, s'utilitzaran les primeres 45 paraules del contingut de l'article.

- Traduir el botó (nou) Manage in Customizer a Gestiona a Personalitza
- Als menús personalitzats, han canviat Links (Enllaços) per **Custom Links**. Traduir mantenint **Enllaços** (no cal afegir personalitzats)
- A Invitacions del node, canviar **Invitacions** per "Envia invitació" (l'actual botó porta a confusió als usuaris)

![seleccio_018](https://cloud.githubusercontent.com/assets/5380649/9989183/a92b03f8-6056-11e5-80f6-25030cda5e51.png)

- Dins d'un node, al definir qui pot penjar documents al Node surt això: 
![seleccio_019](https://cloud.githubusercontent.com/assets/5380649/10016538/01642636-6128-11e5-962b-c5e4475f3eae.png) 

Substituir **Minimum role to associate Docs with group** per "Qui pot afegir documents?" 

Traduccions no urgents: 

- A Categories, canviar **Parent** per "Categoria Mare"
- Canviar **Number of items per page** per "Nombre d'elements a mostrar". La traducció exacte (Nombre d'elements per pàgina) pot confondre a l'apartat Pàgines.
- A l'edició de la pàgina, canviar **pare/mare** per "Pàgina Mare"
- A l'edició de la pàgina, en el combo canviar **(sense pare)** per "(sense mare)"
- A afegeix Carrusel: treure **Add slides to this slideshow by using one of the buttons above** (això és fa amb un espai en blanc a la cadena de traducció).
- A la caixa de ginys de **Amistats** surt aquest text ple d'incorreccions: 

> Una llista dinàmica d'amistats recentment actives, polpulars o noeves del mebre que es mostra. El 
> giny només es mostra s'està veient el perfil d'un membre.

- En el moment de crear un node, surt: 

>Group created successfully.

**Comment by sarjona** [comment]
@jmeler Quan puguis ja ens passaràs la proposta amb la cadena que serveixi tant per Nodes com per XTECBlocs :-)

**Comment by jmeler** [comment]
Quan WP ha de pàginar (per mostrar molts resultats) mostra PAGE. No és exclusiu de BP-DOCS, pasa a WP. 
![seleccio_999 116](https://cloud.githubusercontent.com/assets/5380649/12491150/b03f2e20-c079-11e5-8cab-b48e3fcdf252.png)

**Comment by sarjona** [comment]
Incorporades a la versió 16.03.14

**Comment by jmeler** [comment]
Falta la primera, fer el canvi de text resum a edició d'articles.
Substituir: 

> Els Resums, són textos breus opcionals del contingut escrits manualment que podeu usar al tema. Apreneu més sobre els resums manuals (en anglès).

Per aquest: 
> Si no definiu cap text resum, es mostraran les primeres paraules de l'article.

**Comment by sarjona** [comment]
Actualitzats els fitxers https://github.com/projectestac/agora_nodes/commit/f35baf27aab8bbcc5a5bac2c259de7a0aed1c684
