### ISSUE TITLE
Ginys configurables a cada node

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#222]
Seria molt útil poder personalitzar els ginys a cada node. 
Per exemple:
- El giny de calendari podria ser molt útil per els nodes de departament. 
- Llistat d'enllaços a aplicacions, webs i documents de referència del node. 
- Etc.

Millora implementada relacionada:
https://github.com/projectestac/agora_nodes/issues/169

**Comment by sarjona** [comment]
S'hauria d'afegir la llista de Nodes de forma similar a com apareixen les pàgines. Per fer-ho pot ajudar el canvi que ja es va fer per afegir en general l'apartat de la Xarxa de Nodes (tot i que en aquest cas, la llista de Nodes serà dinàmica).

**Comment by xaviernietosanchez** [comment]
Hem afegit al primer <select> la opció de Node, una vegada afegit al segón <select> surt la opció de escollir tots els nodes (per defecte) i la opció de seleccionar un node concret. 
El llistat de nodes surten de la taula wp_bp_groups.

**Comment by sarjona** [comment]
Resolt al commit https://github.com/projectestac/agora_nodes/commit/303b7901f5e9dc06b32175929732d39cebcf3c54
