### ISSUE TITLE
Graella d'icones amb text es visualitza malament amb mòbils

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#229]
En reduir la mida de la pantalla del navegador o bé en visualitzar en un mòbil un nodes, si la graella d'icones té text posat es visaulitzen els textos en petit en comptes de desapareixer com passava abans. 

Ens ho ha fet arribar en Jesús Ignacio Cañizares a través d'aquest fil de fòrum: http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=69467

**Comment by monicagrau** [comment]
Més informació sobre aquest tema: http://agora.xtec.cat/moodle/moodle/pluginfile.php/213944/mod_forum/attachment/260289/versio%20mobil%20moguda.jpg

**Comment by jmeler** [comment]
De moment, s'han tret els textos sota els icones (com estava originalment) però properament els inclourem amb la mida i posició correcta. Incidència relacionada #224
