### ISSUE TITLE
Invite anyone: error amb les invitacions externes

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#230]
A través d'un fil del fòrum hem vist que sembla que l'extensió "invite anyone" no està funcionant com seria d'esperar. No s'envien els correus i si s'envia algun la pàgina per acceptar la invitació porta a una pàgina que no existeis.

http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=69526

A la pantalla "wp-admin/admin.php?page=invite-anyone&subpage=manage-invitations" no apareix forma d'acceptar invitacions.

S'ha trobat també un fil de debat on es comenta alguna de les errades trobades: https://wordpress.org/support/topic/invitation-requests-page-doesnt-show

**Comment by jmeler** [comment]
Efectivament. La invitació a usuaris externs a la xarxa privada del centre no funciona correctament. Reenvia a una pàgina de registre i falla (el autoregistre "manual") esta deshabilitat a Nodes. 
Les invitacions internes (a membres de la xarxa) sí funciona correctament.

**Comment by sarjona** [comment]
Si el paràmetre general "users_can_register" està desactivat, s'aplicaran els canvis següents al missatge que s'envia a les invitacions:

- Substituir l'enllaç d'activació de http://url/register/?iaaction=accept-invitation&email=xxxxxx@xxxxxx per http://url/nodes/
- Eliminar el text per rebutjar la invitació.

Commit: https://github.com/projectestac/agora_nodes/commit/6e65303c39b2243b1fa98f3be5ac7101a48ea043

**Comment by sarjona** [comment]
S'ha canviat l'enllaç d'activació per aquest altre per garantir que els usuaris acaben arribant a la pàgina especificada:  https://url/wp-login.php?redirect_to=http://url/nodes

Commit: https://github.com/projectestac/agora_nodes/commit/06c4d0511717b98e1c2645d76381518e69a8d490
