### ISSUE TITLE
Giny per afegir una imatge 

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#243]
Actualment, l'usuari ha de fer servir el giny de text i l'etiqueta <img> per adjuntar una imatge. Tot i que es senzill, alguns usuaris troben dificultats. 

Existeix un plugin que podria reunir els requeriments necessaris. 
https://wordpress.org/plugins/image-widget/

S'ha de valorar perquè, en principi, un responsable web d'un centre hauria de tenir coneixements bàsics d'html. Com a mínim les etiquetes **a**, **strong** e **img**.

**Comment by jmeler** [comment]
Estudiar què és millor. Aquesta o la #10

**Comment by sarjona** [comment]
Enlloc d'afegir un giny per imatges només s'han analitzat els que estan referenciats a #10 

- https://wordpress.org/plugins/black-studio-tinymce-widget/
- https://wordpress.org/plugins/wp-editor-widget/


Tots dos afegeixen un giny addicional amb un comportament molt similar (l'única diferència apreciable és que WP Editor Widget té un botó intermig per accedir a la pantalla d'edició de contingut).
S'han realitzat proves de tots dos a Nodes i XTECBlocs i l'únic que funciona als dos sistemes és Black Studio TinyMCE Widget (l'altre deixa crear els ginys però no els mostra a cap de les aparences provades).

**Comment by jmeler** [comment]
Provat Black Studio TinyMCE Widget.
 
- Amb Chrome funciona força bé al personalitzador (barra Personalitza). A Tauler->Ginys, té algun comportament inestable (de vegades no mostra el contingut a la pestanya visual) o desplaça l'editor fora del seu espai natural. 
- Amb firefox (v.35) no es veu el contingut a la pestanya visual però sí que s'afegeix el contingut. S'hauria de comprovar amb versions més actualitzades de Firefox.
NOTA: La versió 35 de firefox és relativament antiga i no funciona correctament amb nodes. Veure issue #433.

**Comment by jmeler** [comment]
Revisar el comportament del Black Studio TinyMCE Widget amb combinació amb el Simple Calendar amb navegador Firefox. 
https://wordpress.org/support/topic/plugin-conflict-with-simple-calendar-google-calendar-plugin-and-firefox

**Comment by sarjona** [comment]
Instal·lar el **Black Studio TinyMCE Widget.** (https://wordpress.org/plugins/black-studio-tinymce-widget/) i revisar els errors que comentava el Xavi als comentaris anteriors.

**Comment by jmeler** [comment]
Issue resolta amb #10
