### ISSUE TITLE
Email Subscribers: Millores

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#245]
* Moure l'item de menú del primer nivell de la barra lateral a un subitem dintre de Paràmetres. Semblant al que es va fer amb tots els plugins del BuddyPress. Es important descarregar la barra lateral (primer nivell). Les subscripcions són importants però una vegada definides, en principi, no es toquen gaire. 
* Crear una pantalla amb els següents elements del menú (similar a com es va fer a WordPress) amb els següents elements: 
  *  Subscripcions
  *  Redacta correu
  *  Envia correu
  *  Notificacions
  *  Correus enviats
  *  Ajuda (enllaça a la PMF)
(S'han tret Cron Mail, Rols i Configuració. A la maqueta, establir els paràmetres més adients per la majoria de les situacions)

![seleccio_006](https://cloud.githubusercontent.com/assets/5380649/9465964/48b2b0be-4b31-11e5-8248-5579693e758b.png)

Pàgina **Subscripcions**
* Treure el botó **Sincronitza email**
* Eliminar l'enllaç a la pàgina oficial 
* Afefir un nou botó **Afegeix grup**
* Subpàgina **Afegir**:  El principal problema d'aquesta pàgina és que "barreja" la creació de usuaris subscriptors amb la creació de grups de subscripció". 2 alternatives:
1) Dividir aquesta pàgina en dos. Una per crear "subscriptors" i un altre per crear grups. 
2) Mantenir una sola pàgina però redissenyar la pàgina separant un concepte de l'altre. També a nivell de funcionament. Si l'administrador no introdueix cap adreça de correu, vol dir que vol crear un grup (ara exigeix un correu per crear un grup, el que no és lògic). 

Si no es fa cap d'aquestes millores, com a mínim deixar clar que es necessari afegir un correu per poder crear un grup nou. 

Pàgina **Redacta**
* Eliminar l'enllaç a la pàgina oficial 

Pàgina **Notificacions**
* Eliminar l'enllaç a la pàgina oficial 
* Subpàgina **Afegeix**: 
*  Treure l'apartat Custom post type
*  Treure l'opció del Cron del desplegable Notification Status

Pàgina **Envia correu**
* Amagar Mail Type
* Eliminar l'enllaç a la pàgina oficial 

Pàgina **Ajuda**
* No hi ha pàgina, és un enllaç a la PMF

**Comment by jmeler** [comment]
Potser canviar **Correus enviats** per **Enviats**. 
No només s'envien correus si no també Notificacions (si seguim la notació del plugin diferencia entre correus "simples" i "notificacions" -correus automàtics quan hi ha un nou post-)

**Comment by sarjona** [comment]
S'han tingut en compte tots els punts excepte el següent:

- A "Susbcriptors" no s'ha afegit el botó "Afegeix grup" ni tampoc s'ha creat la subpàgina especificada.
