### ISSUE TITLE
Graella d'icones: els enllaços locals no funcionen fora de la pàgina d'inici

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#249]
Fora de la pàgina principal, no funcionen els botons de la graella que enllaçen a pagines "locals" (no externes) Mostra "No s'ha trobat contingut". 

La raó és que composa la url a partir de la pàgina principal en lloc de la pàgina d'inici. 

Una incidència semblant: https://github.com/projectestac/agora_nodes/issues/164

Reportat per @ignacioabejaro

**Comment by jmeler** [comment]
De moment, el centre sempre pot definir l'enllaç local com si es tractés d'un enllaç absolut (ficant http:// o https:// al davant). S'obrirà en una altra finestra però és un mal menor.

**Comment by sarjona** [comment]
Aplicat pegat a la versió 15.11.16 perquè els enllaços absoluts obrin el contingut en una finestra nova (codi original) i els relatius mostrin el contingut a la mateixa pestanya.

**Comment by sarjona** [comment]
Revisat també pels SE. Unificat perquè sigui més fàcil de mantenir.
