### ISSUE TITLE
Llegenda desplaçada a galeria de fotos

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#250]
En el mode Galeria del mateix WordPress, es mostra la llegenda de la foto desplaçada a la dreta. Hauria d'estar a sota de la foto. 

![seleccio_999 382](https://cloud.githubusercontent.com/assets/5380649/9576596/62950b10-4fd9-11e5-8afc-ead3229e22b9.png)

**Comment by sarjona** [comment]
Resolta a la versió 15.12.14
