### ISSUE TITLE
Carrusel de notícies

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#251]
Proposta d'afegir un carrusel de notícies a través del fòrum:
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=69986#p261670

**Comment by jmeler** [comment]
La solució manual que proposa el Jaures és força funcional. Tanquem i si varis centres demanen aquesta funcionalitat, la tornem a estudiar. És important mantenir Nodes el més prim possible.
