### ISSUE TITLE
Filtrar per més d'una categoria

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#256]
Si Nodes s'ha de convertir en un concentrador de blogs (d'aula, de projectes, de matèries) ha de tenir la possibilitat de filtrar per categories múltiples. 

Ara només es pot filtrar per una sola categoria (que ja és la categoria del blog). 
Exemple: blog d'aula de 1A que inclou articles de diferents matèries (anglès, matemàtiques, etc.). 
És necessari poder filtrar per ESO 1A i matemàtiques conjuntament

**Comment by jmeler** [comment]
Aquest canvi no és trivial perquè també s'ha d'implementar com seleccionar més d'una categoria a la vegada. Actualment, accedeixes a una categoria fent clic i punt. Es podria plantejar un check en els menús personalitzats de manera que tingui en compte la pàgina de categoria actual.

Exemple: estic a ESO 1A. Creo un menú personalitzat i marco la casella "Concatena categories" (o una denominació similar - s'ha de pensar-), de manera que quan l'usuari faci clic en el item "Matemàtiques" d'aquest menú, Nodes mostri articles d'ESO 1A i a matemàtiques. Si no marquem la casella, només mostra Matemàtiques.

**Comment by jmeler** [comment]
Potser es podria crear una pàgina per construir consultes
http://stackoverflow.com/questions/16665868/filter-posts-by-multiple-checkbox-categories-wordpress

**Comment by jmeler** [comment]
https://wordpress.org/plugins/multiple-category-selection-widget/

**Comment by ignacioabejaro** [comment]
@jmeler Aquesta es la url del plugin que t'havia comentat a la reunió http://docs.designsandcode.com/search-filter/#get

**Comment by jmeler** [comment]
Una primera solució:
http://wordpress.stackexchange.com/questions/27158/wordpress-multiple-category-search

http://yourblog.com/cat=3+7

Es podria millorar perquè en lloc del ID agafes el nom de la categoria. D'aquesta manera, estalviem un pas (anar a mirar l'ID). 

http://yourblog.com/cat=eso1+teatre
http://yourblog.com/category/eso1+teatre

Però aquesta millora la deixem per la fase 2.De moment, aquesta solució ja és prou bona pels usuaris avançats.

**Comment by sarjona** [comment]
Incorporat a la versió 16.02.22.

**Comment by sarjona** [comment]
Resolt al commit: https://github.com/projectestac/agora_nodes/commit/b4f41a4fe2d5894b2a8330a62ac1f27d5a176c17

**Comment by monicagrau** [comment]
Navigate to: http://agora/agora/usu1/categoria/primaria/1r+2n/ or http://agora/agora/usu1/categoria/primaria/1r,2n/

The first one will provide posts that are in both the first AND the second category, the second URL will provide one OR the other.
