### ISSUE TITLE
Millorar les icones

### ISSUE THREAD

**Issue by marc280492** [projectestac/agora_nodes#279]
Bon dia.

M'agradaria fer un parell de suggeriments relacionats amb les icones de NODES (http://agora.xtec.cat/nodes/icones/). Les icones són genials però hi ha algunes coses que penso que en aquest aspecte s'haurien de millorar.

En primer lloc, penso que el fons de la icona del departament de castellà hauria de ser groga i no gris, i el color de la bafarada blanc. Sempre s'ha relacionat aquesta llengua amb aquests colors, i no amb els que hi ha actualment.

En segon lloc, m'agradaria saber per què no hi ha icones de batxillerat a la pàgina http://agora.xtec.cat/nodes/icones/cursos/, si us plau.

Moltes gràcies per la vostra feina.

**Comment by jmeler** [comment]
Hola Marc,
Prenem nota i revisarem els icones. També farem els de batxillerat. 

Gràcies per el comentari

**Comment by jmeler** [comment]
@marc280492 Hola Marc. Disculpa el retard. Hem afegit les icones de batxillerat i hem modificat el de castellà. No era possible blanc sobre groc perquè no tenia prou contrast. He definir un vermell i un vainilla... el "problema" és que català i castellà tenen els mateixos colors.

**Comment by marc280492** [comment]
Gràcies, han quedat fantàstiques! :)
