### ISSUE TITLE
AddToAny: Foto resum a facebook

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#284]
AddToAny inclou la primera foto que troba a la pàgina quan replica a facebook. En lloc de ser la foto de l'article, agafa la foto de la capçalera.

**Comment by jmeler** [comment]
També aplica a XTECBlocs

**Comment by toniginard** [comment]
S'ha afegit suport a l'AddToAny per a OpenGraph, protocol suportat per facebook. Ara s'agafa la imatge resum de l'article sempre i quan faci 200x200 píxels o més (requisit de facebook). Si no hi ha imatge resum o si és més petita que 200x200 (una dimensió o les dues) es continua agafant la imatge de la capçalera.
