### ISSUE TITLE
Caixa de cerca es comporten de manera inconsistent

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#291]
Les caixes de cerca de BuddyPress (Membres, Nodes) semblen deshabilitades. De vegades, es pot escriure (i cercar) i de vegades no.

**Comment by jmeler** [comment]
No és molt crític però és bastant desconcertant

**Comment by sarjona** [comment]
Resolt al commit: https://trello.com/c/zsKAIYqt
