### ISSUE TITLE
Possibilitat de desactivar l'escriptura directa al mur general

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#292]
El mur general permet que els alumnes escriguin directament i la visibilitat és molt gran (els usuaris és lo primer que veuen quan entren). Això permet generar converses molt ràpides i fresques. Dinamitza molt i facilita la participació dels usuaris. 

Precisament per la seva visibilitat i immediatesa, el control és més complicat. No existeix cap figura d'administrador ni moderador com si existeix als nodes.

Seria molt recomanable que el centre pugui decidir si es pot escriure directament al mur general o no. No es tracta d'amagar el mur, que també fa una funció molt important al "replicar" els missatges dels nodes públics. Es tracta d'evitar l'escriptura directa.

Si es molt complicat fer-ho via hook directament al buddypress, es pot amagar la caixa d'escriptura via css.

**Comment by sarjona** [comment]
Una altra opció és fer al canvi al codi i fer un PR als autors del mòdul perquè incorporin aquesta funcionalitat al core.

**Comment by sarjona** [comment]
- S'ha afegit un paràmetre nou per configurar aquesta opció. Per defecte aquest paràmetre permetrà l'escriptura al mur general.
- S'ha afegit una opció "Configuració" al menú de BuddyPress perquè els usuaris administradors tinguin accés directe a l'apartat Paràmetres del BP.
