### ISSUE TITLE
Segon quadre de la capçalera (lema) amb enllaços

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#297]
Petició de la ZER L'Eral (Pep Borràs): en el cas de les ZER, el segon quadre (lema) hauria de permetre enllaçar amb la ZER o amb la població. 

Valorar la possibilitat d'acceptar codi html (< a >) dins del segon quadre (lema).

**Comment by sarjona** [comment]
Resolt al commit: https://github.com/projectestac/agora_nodes/commit/2f7bb21d7d179a24247ff2e2e0e651a5cf644f45


S'ha afegit un camp a **Personalitza | Capçalera** per especificar l'enllaç del bloc descripció/lema.
