### ISSUE TITLE
La galeria ignora el paràmetre de nombre de columnes

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#309]
La galeria de fotos (WordPress) ignora el paràmetre de nombre de columnes
Reportat per Silvia Barrientos: http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=75526

![seleccio_999 009](https://cloud.githubusercontent.com/assets/5380649/11061102/d33e9df6-87a4-11e5-89e0-f9f6fa4f92b8.png)

**Comment by sarjona** [comment]
Resolt
