### ISSUE TITLE
Traducció pàgina Administra el Node | Membres

### ISSUE THREAD

**Issue by pausaura** [projectestac/agora_nodes#311]
La traducció de la primera opció que expulsa i prohibeix l'entrada del membre al Node no hauria de ser "Enderroca & la prohibició".
Tampoc s'hauria de traduir per "degrada" quan un membre perd algun privilegi.
![rols-nodes](https://cloud.githubusercontent.com/assets/14923963/11087810/bac8d3cc-885d-11e5-9364-fbfa38313453.png)

**Comment by sarjona** [comment]
Incorporat a la versió 16.02.01
