### ISSUE TITLE
Els URL de Youtube tipus youtu.be no funcionen al Carrusel

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#316]
Els URL de Youtube tipus youtu.be no funcionen al Carrusel s'han de posar enllaços del tipus youtube.com.....

**Comment by jmeler** [comment]
Una solució senzilla és utilitzar la url del vídeo (l'adreça que es mostra a la caixa d'adreces del navegador) enlloc d'utilitzar l'adreça de compartició (que sí que té aquest format youtu.be que el plugin Carrusel no reconeix). 

No es solucionarà perquè és responsabilitat del plugin (segurament aviat ho solucionaran) i té fàcil solució per part dels usuaris.
