### ISSUE TITLE
Afegir enllaç a Documents al text de l'importador de Intraweb

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#327]
Al final del text explicatiu de l'importació de la intraweb, afegir el següent text:

>  Podeu trobar els documents importats a http://agora.xtec.cat/{nompropi}/docs

On l'adreça ha de ser un enllaç. {nompropi} s'ha de calcular dinàmicament per cada espai. 

Alguns centres no coneixen el repositori de documents de Nodes i pensen que han d'enllaçar els documents un a un des de la mediateca :anguished:

**Comment by jmeler** [comment]
Com a quick and dirty (si no hi ha temps per implementar la ruta) es pot posar el missatge: 

> Podeu trobar els documents importats a /docs

**Comment by sarjona** [comment]
Incorporat a la versió 16.02.01
