### ISSUE TITLE
Calendari amb esdeveniments de més d'un dia

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#331]
Activar a tots els espais el paràmetre que permet resaltar cada dia al calendari quan els esdeveniments són de més d'un dia. Aquest paràmetre ha d'estar activat per defecte. Ara està desactivat i només configurable per xtecadmin. 

![calendar](https://cloud.githubusercontent.com/assets/5380649/11661527/a2e5d9be-9dd2-11e5-9c94-ed211ea149fc.png)

**Comment by sarjona** [comment]
Fa alguns mesos ja es va activar a tots els espais donats d'alta i també a les maquetes.
