### ISSUE TITLE
Revisar la forma en que es ressalten els esdeveniments al calendari

### ISSUE THREAD

**Issue by sarjona** [projectestac/agora_nodes#335]
Al fòrum demanen si es podria revisar la forma en que es ressalten els esdeveniments al calendari:
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=76386#p287269

**Comment by jmeler** [comment]
No aplica amb el nou Simple Calendar (unes boletes marquen que hi han esdeveniments de manera prou clara)
