### ISSUE TITLE
Traduccions BuddyPress

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#336]
Al buddypress o al invite anyone: 
* You must accept your pending invitation before you can access this private group.
![seleccio_999 092](https://cloud.githubusercontent.com/assets/5380649/11806179/9067c5a6-a311-11e5-8ca5-20255616f24d.png)

* Al actualitzar la foto d'un node: 
![seleccio_999 100](https://cloud.githubusercontent.com/assets/5380649/12320826/1216f062-baab-11e5-9aa4-220f2e2bce29.png)

* Al mur d'un node, substituir **Pàgina d'inici** per **Mur**
![seleccio_999 102](https://cloud.githubusercontent.com/assets/5380649/12320987/02c3ca9e-baac-11e5-9a1e-f51b58802c80.png)

* Després d'una estona sense editar un document a BPDocs: 
![seleccio_999 115](https://cloud.githubusercontent.com/assets/5380649/12491040/1a0b51b8-c079-11e5-8662-b9644cd69c74.png)

**Comment by jmeler** [comment]
Quan es rep un petició d'amistat, la notificació diu: 

- Petició de subscripció nova de <Nom del que fa la petició>

hauria de ser:

- Petició d'amistat de <Nom del que fa la petició>

**Comment by jmeler** [comment]
A BuddyPress, pestanya Components, substituir la cade "Connexions de l'amic" per "Amistats"

**Comment by jmeler** [comment]
Modificar Flux d'activitats per "Murs", Nodes d'usuari per "Nodes" i "Connexions de l'amic" per "Amistats"

![2016-02-28_1120](https://cloud.githubusercontent.com/assets/5380649/13378655/65dcab44-de0d-11e5-87f9-d79424731471.png)

**Comment by jmeler** [comment]
Canviar pestanya per el mateix text que posa al botó (Solicitut de pertinença):

![2016-03-20_1853](https://cloud.githubusercontent.com/assets/5380649/13905924/2327b3b8-eecd-11e5-948f-91fa8c5bb808.png)

**Comment by jmeler** [comment]
Canviar el text "Activitat a tot el lloc web" per "Mur general". 

![2016-03-20_1855](https://cloud.githubusercontent.com/assets/5380649/13905941/70235ae6-eecd-11e5-923d-4d7c182f6aa5.png)

El text "Activitat a tot el lloc web" no és correcte perquè només mostra l'activitat als nodes. "Mur general" és més adient, tenint en compte que Facebook és l'absoluta referència en aquest sentit i utilitza la paraula "Mur".

**Comment by jmeler** [comment]
Al mur d'un node, canviar el text "Pàgina d'inici" per "Mur" 

![2016-03-20_1858](https://cloud.githubusercontent.com/assets/5380649/13905960/dd868b4e-eecd-11e5-95f8-85e42824e7ab.png)

Motius semblants a la descripció del comentari anterior.

**Comment by jmeler** [comment]
Falta traduïr els elements del plugin "Invite Anyone"

![2016-04-01_2304](https://cloud.githubusercontent.com/assets/5380649/14220104/4b458ec0-f85e-11e5-9a12-78fa6fe042f6.png)

**Comment by sarjona** [comment]
Incorporat a la versió 16.05.30
