### ISSUE TITLE
Temps per editar al fòrum

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#338]
Amb rol de col·laborador, una vegada creat un tema o una resposta al fòrum, no deixa editar-la. 
A Nodes-centres es va solucionar: https://github.com/projectestac/agora_nodes/issues/120

**Comment by sarjona** [comment]
El pegat es va afegir al connector i, per tant, aquesta incidència no s'hauria de donar (perquè SE i centres compateixen el codi de tots els connectors).

Hem intentat reproduir l'error a la MV però no ho hem aconseguit. Necessitem més informació per poder-ho revisar.

**Comment by jmeler** [comment]
Ok, està solucionat.
