### ISSUE TITLE
Instal·lació del plugin Enhanced media library

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#341]
Des del fòrum de Nodes ens demanen que instal·lem aquest plugin: https://wordpress.org/plugins/enhanced-media-library/

http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=77426

**Comment by jmeler** [comment]
Això pot potenciar l'ús de la mediateca com a repositori de documents, cosa que, en principi, hauriem d'evitar (espai al servidor limitat). La mediateca només ha de servir com a suport per la publicació d'articles i pàgines. BP-Docs és el repositori de documents.

**Comment by jmeler** [comment]
No s'implementarà. És convenient no afegir moltes extensions a Nodes. Només les imprescindibles. La mediateca és només un suport als articles. No es pot convertir en un gestor d'imatges.
