### ISSUE TITLE
Automatitzar publicació imatge resum

### ISSUE THREAD

**Issue by sarjona** [projectestac/agora_nodes#344]
Des del fòrum ens demanem que automatitzem la publicació de la imatge resum: http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=76446

**Comment by sarjona** [comment]
Una possible solució (que cal analitzar i validar, només ho deixo com idea perquè en van parlar a una sessió de WP), és la instal·lació de connectors com Media tools o Auto post thumbnail (que seleccionen automàticament la imatge resum a partir del contingut de l'article).

**Comment by jmeler** [comment]
Implementat. Ara, al crear l'article, la imatge resum es genera automàticament a partir de la primera imatge o vídeo.
