### ISSUE TITLE
No es pot posar un correu a la graella d'icones

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#353]
Arrel d'un missatge del fòrum (http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=78006) s'ha vist que no es pot posar un enllaç del tipus "mailito:correu@correu.domini" ja que afegeix sempre l'URL http://agora.xtec.cat/nomdelnodes al davant.

**Comment by toniginard** [comment]
Resolt a https://github.com/projectestac/agora_nodes/commit/be90997282c6ee0fe19cb84db1ba6c0804f85850
