### ISSUE TITLE
Proposta d'obrir enllaços de la fitxa del centre en finestra nova

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#357]
En aquest fil del fòrum ens proposen que els enllaços de la fitxa del centre s'obrin en una finestra nova: http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=78526#p292909

**Comment by jmeler** [comment]
Aprofito aquest issue per redefinir una part de la fitxa del centre: 
- Al personalitzador, **Identificació del centre**, apartat **Contacte principal**, afegir un nou camp. 
El primer camp es mostrarà a la visualització en el mòbil. Es recomanarà posar el correu electrònic principal. 
El segon camp es mostrarà a la visualització al web i es recomanarà posar la pàgina web de contacte.

**Comment by jmeler** [comment]
@xaviernietosanchez @sarjona @monicagrau  Concreto més la proposta: 

A l'apartat **Contacte principal** han d'apareixer 2 camps: 

- Pàgina de contacte
- Correu electrònic de contacte (opcional)

Aquest dos camps tenen la seva correlació amb les següents vistes: 

- Vista web: l'enllaç **contacte** de la fitxa del centre va lligat amb el paràmetre **Pàgina de contacte**. Si no existeix valor a **Pàgina de contacte**, s'agafa el valor del paràmetre **Correu electrònic de contacte**.
- Vista mòbil: la icona superior del correu (fixada), va lligada al paràmetre  **Correu electrònic de contacte (opcional)** . Si no existeix valor, agafa el valor del paràmetre de la **Pàgina de contacte**.

D'aquesta manera el centre pot definir que vol: 

- Correu electrònic a les dues vistes --> deixar buit el camp Pàgina de contacte
- Pàgina de contacte a les dues vistes --> deixar buit el camp Correu electrònic
- Pàgina de contacte a la versió web, correu a la versió mòbil --> definir els dos camps

Consideracions per adaptar l'actual base de dades (només SQL): 
- El camp **Email o pàgina de contacte** ( emailCentre ) es converteix en: 
-- **Pàgina de contacte** (emailCentre) si és una adreça web
-- **Correu electrònic de contacte** (correuCentre) si és un correu electrònic

Fase2 (implica canvis en el codi): 
- Canviar el nom **emailCentre** a **contacteCentre**

Si teniu qualsevol suggeriment, endavant!

**Comment by toniginard** [comment]
Fixed in commit https://github.com/projectestac/agora_nodes/commit/5023f7cb3d5e7288a1ce8d32fd62b1e905a11904
