### ISSUE TITLE
Plugin per incrustar feeds d'instagram

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#361]
Al fòrum ens demanen el següent:
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=79146

**Comment by jmeler** [comment]
A diferència de Twitter, **Instagram** no és una eina molt popular entre els centres escolars. Tampoc incorpora cap embed per usuari o canal com sí que ho fa Twitter. Es tanca aquesta petició i més endavant, si creixen les peticions, ho tornem a plantejar. 

Si només es vol inserir una foto, es poden seguir [aquestes instruccions](https://help.instagram.com/513918941996087).
