### ISSUE TITLE
Desapareix la icona menú en ocasions

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#367]
La icona del menú despareix en Firefox depenent de les ressolucions de pantalla.
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=79706

**Comment by toniginard** [comment]
El problema consiteix en que quan se superen els 1480 píxels, es fixa l'amplada el body a 1480 píxels i això fa que el div que conté la icona del menú, que té un float:left, salti cap abaix.

**Comment by jmeler** [comment]
Relacionada: 
https://github.com/projectestac/agora_nodes/issues/211

**Comment by jmeler** [comment]
Solucionat. Ara a resolucions més grans de 1480, es visualitza correctament.
