### ISSUE TITLE
BP-Moderation: comentari denunciat amb enllaç incorrecte

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#368]
Al marcar un missatge com inadequat, el missatge s'afegeix a una llista en el panell de control (BuddyPress, Moderació del BuddyPress, Continguts). L'opció més important és poder visualitzar el missatge denunciat (per decidir si esborrar-lo o no). Aquesta opció construeix una adreça incorrecta perquè agafa "activity" com a pàgina de referència de la xarxa. A Nodes aquesta pàgina es diu "activitat" 

![2016-02-28_1008](https://cloud.githubusercontent.com/assets/5380649/13378351/a7fabe44-de03-11e5-9051-fb40929f6ebf.png)

NOTA: Per activar l'opció de moderació és necessari anar a BuddyPress, Moderació del BuddyPress, Configuració i marcar:
- Actualització d'estat
- Comentari d'activitat

**Comment by sarjona** [comment]
Incorporat a la versió 16.03.14
