### ISSUE TITLE
Cerques multietiqueta

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#371]
Actualment, el BP-Docs només deixa "filtrar" per una sola etiqueta. Seria molt útil poder cercar un document combinant etiquetes. 
Per exemple: 

**Programació** de **Matemàtiques** de **2n d'ESO**

(en negreta, les etiquetes)

**Comment by jmeler** [comment]
No implementar fins actualitzar la nova versió de BP-Docs (1.9)

**Comment by sarjona** [comment]
Enviat PR a l'autor perquè inclogui aquesta millora al mòdul: https://github.com/boonebgorges/buddypress-docs/pull/542

**Comment by jmeler** [comment]
Modificar el filtre per defecte perquè sigui **AND** en lloc de **OR**, de manera que si triem **Matemàtiques** i **2n d'ESO** mostri només els arxius que tenen totes dues etiquetes.

**Comment by toniginard** [comment]
Fixed in https://github.com/projectestac/agora_nodes/commit/d121ef9f4f6c18f61adcadc244172293c0c2ae3a
