### ISSUE TITLE
Rol col·laborador pugui afegir codi embed

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#372]
Actualment el rol col·laborador no pot afegir codi "embed" als articles. Revisar també altres etiquetes (iframe etc.)

**Comment by sarjona** [comment]
Resolt al commit: https://github.com/projectestac/agora_nodes/commit/8a6c0480821dba1391add326dbcd1edec0898352

S'ha afegit suport per les etiquetes embed i iframe (que ara només li funcionaven als admin).

**Comment by sarjona** [comment]
Afegit pegat també perquè els col·laboradors només puguin utilitzar etiqueta script pel galleria.io: https://github.com/projectestac/wordpress-mu-common/commit/b145b6627b8062a756f3dcbaebdc81c49e2a60af
