### ISSUE TITLE
Tercer nivell als menús de les pàgines

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#373]
Al fòrum ens demanen si és possible que es pugui fer un 3r nivell dels menús de les pàgines: http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=80286

**Comment by jmeler** [comment]
No es farà, l'espai a la barra de pàgines és insuficient. És conveniente no pasar del segon nivell i això por incentivar 3 i 4 nivells.
