### ISSUE TITLE
Destinació nova pestanya no funciona 

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#375]
Al menús, tot i que l'enllaç sigui absolut i estigui marcada l'opció "Obre l'enllaç en una finestra o pestanya nova", l'enllaç s'obre sobre la mateixa pestanya. 

![seleccio_999 171](https://cloud.githubusercontent.com/assets/5380649/13809366/cd78a194-eb6a-11e5-8db7-9eb596548f5c.png)

NOTA: El funcionament al menú ha de ser independent de la graella d'icones (on la discriminació es fa per url absoluta o relativa).

**Comment by jmeler** [comment]
A Nodes funciona correctament.

**Comment by sarjona** [comment]
Integrat a la versió 16.03.30
