### ISSUE TITLE
L'amplada de la columna dreta és com la de l'esquerra

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#376]
En configurar el nodes amb dues columnes o columna dreta l'amplada és més gran que la graella d'icones. Abans aquesta columna tenia la mateixa amplada que la graella.
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=80586#p300090

A banda, també es veu malament la graella d'icones quan el text té més d'una línia:
http://agora.xtec.cat/ceip-paucasals-sjdespi/

**Comment by sarjona** [comment]
A la versió 16.03.30 va quedar resolta la incidència i només queda fer un desplegament per solucionar-ho també pels centres que tenen només la columna de la dreta activa (que ja està resolt i només queda pujar els canvis).
