### ISSUE TITLE
Redimensionament incorrecte de les targetes

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#377]
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=80586#p300349

És freqüent que es redimensioni la targeta abans de carregar el contingut. No té relació amb el carrusel. Pot passar amb qualsevol contingut.

Només passa la primera vegada que es carrega la pàgina ja que després (si feu F5) la caché ajuda a que es carreguin més ràpid el contingut.

![captura castanyada](https://cloud.githubusercontent.com/assets/900389/13877261/ed75e588-ed09-11e5-9be6-0077628dc59b.JPG)

**Comment by jmeler** [comment]
La captura a la descripció crec que correspon a un altre error (distribució del thumbnail) quan només hi ha un article per fila. Adjunto captura de l'error al que fa referència la issue. 
![2016-03-17_2033](https://cloud.githubusercontent.com/assets/5380649/13905818/b195a1a8-eeca-11e5-9d9c-beb1dc1ee2f6.png)

**Comment by sarjona** [comment]
La incidència del redimensionament ja va quedar resolta a la versió 16.03.30

La incidència de la primera captura de pantalla quedarà solucionada al proper desplegament.
