### ISSUE TITLE
Usuari admin sense permisos per restaurar pàgines de buddypress

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#382]
Quan un usuari administrador esborra (per error) una de les pàgines base que fa servir **BuddyPress** (Activitat, Membres, Nodes), **BuddyPress** mostra un enllaç que dona accès a la pàgina de configuració. Aquesta pàgina de configuració es accessible pel superadministrador però NO per un administrador. 

Modificar els permissos perquè un usuari amb rol d'administrador pugi accedir.

**Comment by jmeler** [comment]
Es mantindrà oculta perquè ja no es poden esborrar les pàgines. 
Fer consulta a BBDD per revisar si algun centre ha esborrat les pàgines.

**Comment by sarjona** [comment]
Amb SQL no és trivial obtenir aquesta informació perquè:

- Es pot obtenir la llista de pàgines (_SELECT option_value FROM wp_options WHERE option_name='bp-pages'_), però la informació està serialitzada.
- Després d'obtenir aquesta informació, cal comprovar si existeix o no l'identificador de cadascuna de les pàgines a la taula wp_posts (per exemple, _SELECT * FROM wp_posts WHERE id=5_).

Per tant, es tanca la petició i si algun centre es troba el problema, ja li solucionarem manualment (com hem fet fins ara amb els que ho han comunicat que, a priori, no haurien de ser gaires).
