### ISSUE TITLE
Miniatura de l'enllaç amb rol de col·laborador

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#384]
Actualment, si no ets usuaris administrador, no pots penjar un enllaç al mur amb la funcionalitat de generar miniatura automàtica. Modificar permisos perquè sigui possible.

**Comment by sarjona** [comment]
S'ha resolt la incidència executant SQL següent:

`UPDATE wp_options SET option_value=3 WHERE option_name='comment_max_links'`

Queda pendent executar-ho també a l'entorn de formació quan estigui disponible el servidor.
