### ISSUE TITLE
Traduccions

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#386]
Al afegir un usuari ja existent a una llista mostra: 

![2016-04-01_2133](https://cloud.githubusercontent.com/assets/5380649/14217957/7d66c84a-f851-11e5-9dc8-9b09b1f159c2.png)

Hauria de dir "L'usuari ja existeix a la llista"

**Comment by jmeler** [comment]
Al esborrar un subscriptor: 
![2016-04-01_2150](https://cloud.githubusercontent.com/assets/5380649/14218352/e35295a6-f853-11e5-8679-67667af01bd2.png)

**Comment by jmeler** [comment]
En varies pantalles apareix la paraula "Envia" en el botons de desar. Canviar per "Desa". El botó "Envia el missatge" es pot mantenir igual. 
![2016-04-01_2211](https://cloud.githubusercontent.com/assets/5380649/14218819/e46177de-f856-11e5-88be-e90b4e4566de.png)

**Comment by jmeler** [comment]
Canviar "Adreça de notificació" per "Plantilla de notificació"
![2016-04-01_2210](https://cloud.githubusercontent.com/assets/5380649/14218898/5e11258e-f857-11e5-891d-6911983c8697.png)

**Comment by jmeler** [comment]
Canviar "Email subscribers" per "Subscripcions"
![2016-04-01_2218](https://cloud.githubusercontent.com/assets/5380649/14218995/f0e5af7e-f857-11e5-8645-e729c3c92939.png)

**Comment by jmeler** [comment]
Treure la paraula "Article Personalitzat".

![2016-04-01_2258](https://cloud.githubusercontent.com/assets/5380649/14219949/5648123a-f85d-11e5-84dc-79e0836fb34f.png)

**Comment by sarjona** [comment]
Revisat al commit https://github.com/projectestac/wordpress-email-subscribers/commit/76cb1b020298c6a18cf751aa1518b7c0e45d75b7
