### ISSUE TITLE
Amagar opcions de la secció Paràmetres

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#387]
És convenient reduir elements de la barra lateral d'administració (que comença a estar molt carregada, especialment la secció Paràmetres). Tenir moltes opcions atabala als usuaris. 

Al menú de la barra lateral, apartat **Paràmetres**:
- Amagar **Activity Plus**.  Ja està present (i millor contextualitzat) a la pàgina d'opcions de BuddyPress. 
- Amagar o treure **SlideShare**. WordPress admet Slideshare com oEmbed. Simplement enganxant l'adreça, el slideshare apareix. Imagino que s'ha mantingut per compatibilitat amb XTECBlocs. A Nodes no és necessari. 
- **Convida Membres**: Ja esta present a BuddyPress - Invite Anyone

**Comment by sarjona** [comment]
Integrat i pendent de desplegament: https://github.com/projectestac/agora_nodes/commit/5ce8736fb552c041eea8680c374bf583c06e3669
