### ISSUE TITLE
Emisor del missatge

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#388]
L'adreça de l'emisor del missatge ha de ser l'adreça de l'administrador del Nodes configurada a **Paràmetres**, **General**. 
Actualment l'emisor del missatge és apligest@correueducacio.xtec.cat amb un no reply. 

Això pot generar malentensos i problemes. En molts casos, la família contestarà igualment el missatge rebut i no sabrà interpretar el Mail delivery failed. No és suficient amb especificar-ho en el missatge, la inercia de contestar un correu és molt gran, sobretot en usuaris amb poca competència digital. 

Aquesta incidència s'ha de resoldre abans del 1 de setembre (començament de curs 2016-17).

**Comment by sarjona** [comment]
El paràmetre ja existia al mòdul d'enviament de correu però estava amagat pels administradors. S'ha revisat aquest paràmetre per tal que ara els administradors puguin canviar-lo:

![correu_replyto](https://cloud.githubusercontent.com/assets/900389/14485603/54a5f862-0158-11e6-9a3b-9a818b4be3cd.png)

Resolt al commit: https://github.com/projectestac/agora_nodes/commit/a907052524165e3ec55373994d8643f94c2bf8f5

Cal tenir en compte que, per defecte, el valor d'aquest paràmetre és agora-noreply@xtec.cat i, per tant, els centres hauran de canviar-ho manualment perquè aparegui un altre personalitzat.

Per aquest motiu, s'ha afegit un altre pegat al commit https://github.com/projectestac/agora_nodes/commit/472c9ccb13e634a534c70acdbcb7b75f3d20903a per agafar el Reply-To specificat al header del missatge en cas que existeixi (per exemple, email-subscribers ho té). D'aquesta forma, el comportament actual ha quedat de la forma següent:

- S'ha habilitat l'opció als centres perquè puguin definir l'adreça de correu que ha d'aparèixer per defecte quan el sistema enviï un missatge de correu (per exemple, per recuperar la contrasenya).
- S'ha modificat el mòdul d'enviament de correu perquè, quan als headers de la petició hi hagi definit el Reply-to l'agafi i el faci servir enlloc del paràmetre per defecte anterior. 
- En el cas de l'email-subscribers, Reply-to sempre existeix i té com a valor el de la persona que fa l'enviament (com a mínim pels butlletins).
