### ISSUE TITLE
Error HTTP en pujar un arxiu a un document

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#389]
No es pot pujar un arxiu adjunt a un document navegant amb http. 
![2016-04-02_1545](https://cloud.githubusercontent.com/assets/5380649/14226724/a6d80f6a-f8ea-11e5-81c2-29c0671a485b.png)

Com a mesura paliativa, els usuaris poden reescriure la url afegint https i editar de nou el document. Amb protocol https funciona correctament.

**Comment by sarjona** [comment]
@jmeler Es va afegir fa un temps un pegat perquè, en accedir a les pàgines d'edició dels documents on apareixia el formulari de pujada de fitxers, la navegació es fes per HTTPS. Ens podeu indicar la seqüència de passos exactes que cal seguir per reproduir l'error? Des d'on ho hem provat, la redirecció a la pàgina HTTPS s'ha fet automàtica i, per tant, hem pogut pujar correctament els fitxers.

**Comment by sarjona** [comment]
Resolt al commit https://github.com/projectestac/agora_nodes/commit/1652994b84aa9433c6fc1fe80ae0aea3c461d771
