### ISSUE TITLE
Afegir textarea amb urls d'imatges com a font

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#392]
Afegir un textarea on enganxar una llista d'urls d'imatges. 
Amb aquesta extensió, ja no caldrà dependre de que el proveïdor vulgui habilitar les rss...

https://chrome.google.com/webstore/detail/album/obknigmaekkacdkckfeegcfiefdaeked

**Comment by sarjona** [comment]
- El camp de text apareixerà per sobre dels camps RSS i Google+ actuals.
- S'afegirà un enllaç a la PMF del connector 
- Si és possible, també estaria bé afegir algun paràmetre per poder amagar RSS/Google+ via base de dades per si algun dia deixen de funcionar no haver de fer pujada exprés.

**Comment by sarjona** [comment]
Resolt al commit: https://github.com/projectestac/wordpress-slideshow-jig/commit/9984e028a90e809bc199a7b5f50f30ef25382364
