### ISSUE TITLE
Imatge no s'insereix

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#393]
En el moment de crear un nou document, si afegim una imatge amb **Insereix** | **Add Media**, la imatge queda en estat "S'està penjat la imatge" i mai acaba de penjar-se. 

Si desem el document i tornem a inserir, la imatge apareix a la mediateca  i es pot inserir sense problemes.

Provat amb usuari col·laborador, Linkat 14.04, Chrome Versió 43.0.2357.81 (64-bit)

**Comment by jmeler** [comment]
Amb @monicagrau veiem que el problema és el filtre/filtres que apareixen a dalt de la mediateca. Si es torna a seleccionar els valors dels filtres, les imatges es poden seleccionar i inserir.

**Comment by jmeler** [comment]
Amb rol col·laborador no es veuen les imatges (provat a acc)

![image](https://cloud.githubusercontent.com/assets/5380649/15713476/e32b5700-2816-11e6-888f-9401e6930833.png)

**Comment by sarjona** [comment]
Aquesta darrera incidència incidència de que "no es veuen les imatges" s'ha resolt a INT i quedarà resolta també a PRO i FRM (és la mateixa que la que es donava a la imatge resum i que es dóna a causa d'un error de WP 4.4.3: https://wordpress.org/support/topic/thumbnails-broken-after-44-upgrade

**Comment by sarjona** [comment]
Resolt al commit https://github.com/projectestac/wordpress-buddypress-docs/commit/28d91b2706c04606035a5265e00cfaf1b1e32005 que ja es va desplegar ahir a producció.
