### ISSUE TITLE
Millores BP-Docs

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#394]
BP-Docs pot convertir-se en un bon gestor documental pels centres. Té algunes limitacions però algunes avantatges. 

La nova versió 1.9 incorpora carpetes dins de grups (nodes). 

Després de provar que la versió 1.9 funciona ok amb nodes, s'hauria d'implementar algunes millores: 

- Filtratge multietiquetes: #371 
- Suggeriment d'etiquetes: #135 
- Solució d'alguns errors: #389 #393

**Comment by sarjona** [comment]
Actualitzat el submòdul a la 1.9.0
