### ISSUE TITLE
Provar-ho

### ISSUE THREAD

**Issue by jomenci28** [projectestac/agora_nodes#398]
Hola, tinc un hosting i he vist que això és de distribució lliure i m'agradaria poder-ho provar ja que de fet, ja tinc un domini i encara que el meu centre ja té nodes m'agradaria utilitzar-ho per posar els enllaços als alumnes i tal...

jo pregunto: és possible tenir nodes al meu propi hosting? he intentat de baixar-me els fitxers, pujar-los al hosting i crear la base de dades i no me'n surto, la pàgina d'instal·lació no carrega,

moltes gràcies.

**Comment by sarjona** [comment]
Hola!

Has tingut en compte les explicacions del fitxer INSTALL.txt? https://github.com/projectestac/agora/blob/master/INSTALL.txt

Una abraçada,
Sara

**Comment by jomenci28** [comment]
Hola,
Suposo que he de seguir els passos de "WORDPRESS Installation".
Pujo el contingut de html/wordpress al public_html del meu hosting, creo la base de dades 'usu1' amb phpAdmin, importo el contingut de sql/mastersec.sql a la base de dades 'usu1' i no sé com reemplaçar "http://pwc-int.educacio.intranet/agora/masterpri/"
per "http://yourserver/pathtoyourwordpressinstallation/", aquí em quedo trabat. Tot i que he provat d'entrar al web sense realitzar els passos i no carrega, es queda amb 'Página no dispobible'.
Suposo que després hauré d'extreure el contingut de sql/mastersec.zip i posar-lo a la carpeta public_html/wpdata/usu1 (si no hi és, crear-la) i repetir tots els passos amb usu2, usu3 i usu4.
Tot i que no entenc perquè he de crear quatre bases de dades, ni com donar-li els paràmetres de les bases a la instal·lació de wp perquè carregui correctamet i pugui seguir amb la instal·lació.

moltes gràcies per tot,

una abraçada,

Josep

**Comment by jomenci28** [comment]
Hola, 
ara m'ho he mirat amb tranquil·litat i el que entenc és que he de substituir a per tot on hi posi "http://pwc-int.educacio.intranet/agora/masterpri/" per "http://yourserver/pathtoyourwordpressinstallation/".

Però que "http://pwc-int.educacio.intranet/agora/masterpri/, ha de ser elmeudomini.com (en cas que ho vulgui tenir directament a public_html), correcte?

L'únic que no entenc és perquè he de fer-ho amb 4 bases de dades -usu1, usu2, usu3, usu4-.

moltes gràcies per tot!!

Josep
