### ISSUE TITLE
Extensió TOC+

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#405]
Anàlisi, integració i validació de la extensió TOC+
https://wordpress.org/plugins/table-of-contents-plus/

Petició del CRP de l'Alt Penedès (Pilar Mata)

**Comment by jmeler** [comment]
Validada. Molt bona extensió amb [moltes opcions](http://dublue.com/plugins/toc/#Shortcodes) ben ordenades.

Modificacions que s'han de fer per: 

1. Cal afegir aquesta regla css (al fitxer styles del tema) per evitar vores a la caixa d'index (Nodes millor sense vores). 

#toc_container {
    background: #EFEFEF;
    border: inherit;
}

2. Heading text

![image](https://cloud.githubusercontent.com/assets/5380649/16681744/dfa2a712-44f6-11e6-9739-0a331c501647.png)

3. Amagar secció Main Options -> **Presentation**

**Comment by sarjona** [comment]
@jmeler Cal afegir aquesta extensió també a XTECBlocs?
