### ISSUE TITLE
No aconsegueixo fer funcionar la instal·lació

### ISSUE THREAD

**Issue by jomenci28** [projectestac/agora_nodes#409]
Bones, ja tenia un tiquet (https://github.com/projectestac/agora_nodes/issues/398) però com no he trobat la manera de reobrir-lo, n'obro un de nou.

A veure, he estat remenant i he seguit tots els passos, ho especifico:
1.- He copiat els fitxers de html/wordpress al public_html de la meva pàgina.
2.- He modificat l'arxiu 'mastersec.sql' tot reemplaçant "http://pwc-int.educacio.intranet/agora/masterpri/", pel meu domini, amb http:// davant i l'extensió al final.
3.- He creat la base de dades usu1 i hi he pujat el contingut de mastersec.sql modificat i he duplicat la base de dades 3 cops, amb els noms 'usu2', 'usu3' i 'usu4', tal i com s'indica en el fitxer INSTALL.txt
4.- M'he baixat el fitxer sql/masterxxx.zip, l'he extret i he copiat el seu contingut al directori que he creat al meu public_html/wpdata/usu1. He duplicat aquesta carpeta 3 cops, amb els noms 'usu2', 'usu3' i 'usu4'.
5.- He entrat a la pàgina principal i em continua diguent que no està disponible.
Què estic fent malament? Com és que s'han de crear 4 bases de dades? No hauria de configurar el fitxer wp-config.php diguent-li els noms de les bases de dades?
No sé què estic fent malament, no sé si em podrieu orientar,

moltes gràcies!

Josep

**Comment by toniginard** [comment]
Hola Josep,

El codi d'Àgora és un paquet força gran amb múltiples interaccions internes. El sistema està concebut com a una plataforma a on hi ha múltiples espais que es gestionen des del portal. És aquí, al portal, a on hi ha una eina per corregir fàcilment els URL. Però atès que només t'interessa la part de Nodes, el més pràctic seria que agafis un WordPress estàndard i hi afegeixis les extensions i temes de Nodes.

Si ho fas d'aquesta manera, podràs utilitzar el nom de base de dades que vulguis i no tindràs el problema dels usuX. Senzillament, has d'utilitzar el _wp_config.php_ original i posar-li les dades d'accés a la teva base de dades.

Si corregeixes els valors de _siteurl_ i _home_ de la taula _wp_options_, t'hauria de deixar de sortir l'error, tot i que, internament, la majoria de continguts no estaran bé i donaran error en visitar-los. Ara bé, els continguts nous funcionaran. 


Salutacions,

Toni

**Comment by jomenci28** [comment]
Moltes gràcies! Ara ho provaré...
I en cas que volgués instal·lar el tema i extensions de Nodes, on puc trobar el tema i el nom de les extensions?

Salutacions,

Josep

**Comment by toniginard** [comment]
Hola Josep,

Pots descarregar el paquet sencer de la darrera versió publicada d'Àgora en aquesta pàgina: https://github.com/projectestac/agora/releases

T'has de descarregar el fitxer _agora_vxx.xx.xx.zip_ o el _agora_vxx.xx.xx.tar.gz_ (el contingut és el mateix) i copiar els fitxers que t'interessin. El WordPress es troba dins de _html/wordpress/_.


Salutacions,

Toni

**Comment by jomenci28** [comment]
Moltes gràcies! Vaig a provar-ho i et dic quelcom,

una abraçada,

Josep

**Comment by jomenci28** [comment]
Hola,

m'ho he descarregat i he copiat la carpeta reactor (el tema) a la carpeta /wp-content/themes però quan l'activo em diu error 500 i la pàgina ja no funciona.
He de desinstal·lar wp i tornar-hi i si ho torno tampoc funciona. També he provat d'instal·lar el tema pujant la carpeta en format .zip a l'apartat "Instal·la"/"Puja tema" de l'administració de wp i tres quarts del mateix: en activar el tema, deixa de funcionar.

No em vull fer pesat, però... em podríeu indicar què estic fent malament?
La versió de WP és 4.2.7, tal i com posa a les instruccions de l'enllaç que m'has enviat,


moltes gràcies,

cordials salutacions,

Josep

**Comment by toniginard** [comment]
Hola Josep,

El tema _reactor_ es fa servir com a base per als altres dos. Per tant, has de copiar també, com a mínim, el directori _reactor-primaria-1_ o el directori _reactor-serveis-educatius_ al directori _themes_.

D'altra banda, et recomano que pugis els fitxers via FTP (si la instal·lació és en un servidor remot) o que els copiïs directament (si és en local). Nosaltres no utilitzem les opcions d'actualització automàtica del WordPress i, de fet, les tenim desactivades al nostre _wp_config.php_, ja que ens fan perdre el control del codi.


Salutacions,

Toni

**Comment by jomenci28** [comment]
Moltes gràcies,

ho provo i et dic quelcom, és que vaig bastant perdut amb això...

Josep

**Comment by jomenci28** [comment]
Provat i continuo rebent el 500 internal server error... 
aquest tema necessita d'algun plugin per funcionar?

merci,

Josep

**Comment by jomenci28** [comment]
He seguit les teves instruccions de http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=81146&parent=302789 i em surt l'error 

> include_once

 dirname(__FILE__) . '/wp-includes/xtec/lib.php'; global $isAgora, $isBlocs; $isAgora = true; $isBlocs = 

> false;
He mirat i l'arxiu lib.php, hi és a /wp-includes/xtec/.
El codi 

> include_once dirname(__FILE__) . '/wp-includes/xtec/lib.php';
global $isAgora, $isBlocs;
$isAgora = true;
$isBlocs = 

> false; ja hi és, a l'inici de l'arxiu wp-config.php i surt aquest error. El codi és enganxat just al començament del fitxer.

merci per tot,

Josep

**Comment by jomenci28** [comment]
Per fi! Aconseguit, no us molesto més! ;)


gràcies per tot!

Josep

**Comment by jomenci28** [comment]
Una ultima pregunta,

fer ús d'aquesta plantilla per finals educatius és correcte? és que com que he vist que és de llicència lliure, volia preguntar si jo en puc fer ús, ja que porta els segells de la Generalitat i l'XTEC i no sé si és ben bé correcte fer-ne ús i m'agradaria que m'ho poguéssiu aclarar.

Moltes gràcies !!


Josep

**Comment by toniginard** [comment]
Hola Josep,

Tot el codi és programari lliure i, per tant, el pots utilitzar pel que vulguis. En el cas dels logotips de la Generalitat i de la XTEC, els pots utilitzar si el lloc web és per a un centre que depèn del Departament d'Ensenyament. En altres casos, hauries de canviar els logotips.


Salutacions,

Toni

**Comment by jomenci28** [comment]
OK, perfecte. El web és per usar en un centre que depèn del Departament d'Ensenyament però no és la pàgina principal d'aquest, sinó per penjar recursos als alumnes i notificar-los amb publicacions,


moltes gràcies,

Josep
