### ISSUE TITLE
Interlineat incorrecte

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#412]
![image](https://cloud.githubusercontent.com/assets/5380649/15351059/73d2e524-1cdd-11e6-9715-8dc44f1e56ce.png)

El reactor té un estil amb un line-height: 0 per alguns formats (vídeo, image, link) que a Nodes no s'utilitzen (ni es poden configurar) però que sí que es poden heredar al importar els articles des de un WordPress. 

La solució senzilla passa per sobreescriure l'estil amb: 

.post.format-audio p, 
.post.format-gallery p, 
.post.format-image p, 
.post.format-link p, 
.post.format-video p {
    line-height: 1.6em;
}

**Comment by jmeler** [comment]
Només aplica a Nodes, no a xtecblocs

**Comment by monicagrau** [comment]
Xavi,
sembla que l'afectació també es dóna dins dels articles. Quan hi ha un vídeo i text el text no es mostra.

Hola, Mònica!

Gràcies per solucionar-ho. Efectivament, es tracta d'arxius importats de wordpress, però hi ha casos en què no s'ha solucionat del tot. 

http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=82606
