### ISSUE TITLE
Categories es veuen buides

### ISSUE THREAD

**Issue by jomenci28** [projectestac/agora_nodes#416]
Hola,

faig servir la plantilla reactor a la meva instal·lació de WP 4.5 ja fa uns dies i m'ha encantat, tot i que encara hi ha una cosa que no entenc i espero que m'hi podeu ajuda, i és que, en qualsevol novetat que està dins una categoria, a la portada, si faig clic al nom de la categoria, em surt una pantalla buida amb el nom de la categoria a la part superior dreta. La meva instal·lació és http://www.idelegat.tk/
En podeu veure un exemple a http://www.idelegat.tk/category/eso/eso-2/eso-2a/

Per altra part us volia demanar com aconseguir que a la portada tingués dos articles per fila, i no pas un per fila i els botons de compartir WApp, Fb, Twter i GMail.

Gràcies per tot! 

Una abraçada,

Josep

**Comment by toniginard** [comment]
Hola Josep,

Pel que fa als problemes en accedir a les categories, és possible que et falti copiar els directoris següents:

- html/wordpress/wp-content/mu-plugins/
- html/wordpress/wp-includes/xtec/

Pel que fa a tenir dos articles per pàgina a la portada, es configura a Tauler | Aparença | Personalitza | Pàgina d'inici

I pel que fa als botons per compartir, comprova que tinguis activada l'extensió "AddToAny Share Buttons". En cas de dubte, baixa't la versió original (la nostra té algunes personalitzacions): https://wordpress.org/plugins/add-to-any/ i canvia'n els fitxers.


Salutacions,

Toni Ginard

**Comment by jomenci28** [comment]
Hola,

moltes gràcies per la ràpida resposta! però és que... tens raó en que no tinc copiada la capeta mu-plugins però és perquè en copiar-la dins wp-content la pàgina no carrega i em mostra Error 500, potser hi ha quelcom no compatible amb la meva versió de WP...

Moltes gràcies per l'AddToAny i la configuració de la pàgina principal, que em funciona a la perfecció,


una abraçada,

Josep

**Comment by toniginard** [comment]
Tens accés als logs del servidor web? Ajudaria saber més detalls de l'error. "Error 500" vol dir que s'ha produït un error en el servidor, però sense més detalls és difícil fer res.


Toni

**Comment by jomenci28** [comment]
Ja he tardat molt a contestar, però és que no hi veig cap error relacionat amb l'hora que me'l dona. Cal afirmar que l'error no és la típica pàgina "500 Internal Server Error", sinó que em surt des del navegador, amb lletres petites.

Potser és que això dels mu-plugins s'ha d'activar o no és compatible amb el meu servidor, ja que la carpeta no hi és, dins wp-content, al meu servidor...

moltes gràcies!

Josep

**Comment by toniginard** [comment]
Hola Josep,

De la teva resposta interpreto que no tens accés als _logs_ de l'apache, cosa que dificulta el diagnòstic.

Al directori mu-plugins hi ha dos fitxers que carreguen funcions addicionals: _agora-functions.php_ i _common-functions.php_. Hauríem d'intentar esbrinar quin dels dos et dóna l'error. Treu-los d'un en un i mira si et segueix fallant. Quan sapiguem quin és el fitxer problemàtic, intentarem trobar el punt del codi que genera l'error.

Salutacions,

Toni Ginard

**Comment by jomenci28** [comment]
Fet: el que dona error és "common-functions.php"

Gràcies,

Josep

**Comment by jomenci28** [comment]
Ara tinc la carpeta mu-plugins sense aquest fitxer i ja es veuen les categorieees!!!


moltes grààcies!

ja funciona,

una abraçada,

Josep

**Comment by jomenci28** [comment]
Ara ja funciona, però he estat mirant i he trobat l'error,

ara ja em funciona fins i tot amb el fitxer common-functions.php i he mirat el seu interior i he vist que anava a buscar un fitxewr anomenat "lib.php" dins la carpeta wp-content/mu-plugins/common i aleshores he entrat a common i he vist que per raó X no hi havia cap fitxer, aleshores me'ls he descarregat del repositori GitHub i ara ja funciona,

moltes gràcies per tot!

Josep

**Comment by toniginard** [comment]
Perfecte, Josep! Tanquem el tiquet.

**Comment by jomenci28** [comment]
gràcueees

El dimarts, 7 de juny de 2016, Toni Ginard <notifications@github.com> va
escriure:
