### ISSUE TITLE
Millora estètica en la presentació dels articles

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#418]
> [..] ara mateix la foto queda totalment enganxada al títol de sobre i al text de sota. Hi ha manera de deixar un espai entremig? D'altra part, la imatge queda lleugerament més estreta que el text. No seria millor alinear-los a sang?

Font original: 
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=83306

**Comment by jmeler** [comment]
![image](https://user-images.githubusercontent.com/5380649/29168681-433ae56a-7dd0-11e7-9de6-6fa44acdda84.png)

**Comment by jmeler** [comment]
Afegir aquests estils: 

.entry-thumbnail {
    margin: 10px 0 15px 0;
}

.entry-body .columns{
 padding:0px
}
