### ISSUE TITLE
Petició icona "Enllaços educatius"

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#419]
Al fòrum ens demanen una per a l'IOC:
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=83446

**Comment by jmeler** [comment]
Afegir també enllaça a Banc de recursos del serveis educatius (BDR)

**Comment by monicagrau** [comment]
Al fòrum ens demanen també afegir "Esfer@" -> http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=95707

**Comment by jmeler** [comment]
Redirigida a #574
