### ISSUE TITLE
Imatge resum automàtica

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#426]
Moltes vegades, la primera foto de l'article és una bona candidata per ser imatge resum.

- Generar la imatge resum a partir de la primera foto de l'article. 
- Generar la imatge resum a partir del primer vídeo.

Relacionada amb #344

Consideracions: 
- La imatge resum es genera cada vegada que es **publica** l'article. Si l'usuari no vol imatge resum, pot esborrar la imatge resum una vegada publicat l'article. 
- Si es publica l'article i no conté cap foto, no es genera cap imatge resum. Si després l'usuari afegeix una foto a l'article i vol que s'autogeneri la imatge resum, ha de canviar l'estat de l'article del mode publicat a esborrany i després a publicat un altre cop. En altres paraules, només s'autogenera la imatge resum quan es passa a estat **Publicat**.
- La primera foto de l'article pot ser una imatge local (mediateca) o externa. Veure implicacions. 
- Vimeo i Youtube tenen adreces o apis per generar imatges a partir del vídeo. 
- Esgotar la opció hook abans de valorar plugins.

**Comment by jmeler** [comment]
Ideas: 
` // youtube?

    if (strstr($content,"youtube")){
        if (preg_match('%(?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i', $content, $result)) {
            return 'http://img.youtube.com/vi/'.$result[1].'/mqdefault.jpg';

    } `

**Comment by jmeler** [comment]
Un possible punt de partida: 
https://paulund.co.uk/automatically-set-post-featured-image

**Comment by toniginard** [comment]
Fixed in commit https://github.com/projectestac/agora_nodes/commit/9b342b52966eeea339fb702e4fae87bd82a58fd9

**Comment by monicagrau** [comment]
Aquest canvi no ha d'aplicar a XTECBlocs ja que depenent del tema triat queda bastant malament.
