### ISSUE TITLE
Codi embed de Picasa es modifica en canviar a "Visual"

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#432]
Si s'enganxa el codi embed de Picasa a la pestanya "Text" però abans de desar es passa a la pestanya "Visual" el codi queda modificat. (A Wordpress 4.2 això no passava).

http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=84466

**Comment by jmeler** [comment]
@frncesc ens envia aquesta possible solució: https://ca.wordpress.org/plugins/preserved-html-editor-markup-plus/

**Comment by jmeler** [comment]
És un tema del tinymce que filtra, per seguretat, alguns elements i atributs. És poden [ afegir](https://www.tinymce.com/docs/configure/content-filtering/#valid_elements) més elements i atributs mitjançant aquest hook: 

```
function my_change_mce_options( $init ) {
    // Command separated string of extended elements
    $ext = 'embed[flashvars]';

    // Add to extended_valid_elements if it alreay exists
    if ( isset( $init['extended_valid_elements'] ) ) {
        $init['extended_valid_elements'] .= ',' . $ext;
    } else {
        $init['extended_valid_elements'] = $ext;
    }

    // Super important: return $init!
    return $init;
}

add_filter('tiny_mce_before_init', 'my_change_mce_options');
```
En el exemple, he afegit el flashvars, atribut del embed de picasa que dona el problema però val la pena afegir aquest tipus de excepcions per facilitar la inclusió d'objectes obsolets de flash? Més aviat que tard, deixaran de ser compatibles amb els navegadors actuals.

**Referències:**

https://www.tinymce.com/docs/configure/content-filtering/#valid_elements
NOTA: No es pot modificar directament al plugin que tenim TinyMCE advanced. Cal un [plugin](https://wordpress.org/plugins/advanced-tinymce-configuration/) o el hook d'abans (font:
http://www.engfers.com/2008/10/16/how-to-allow-stripped-element-attributes-in-wordpress-tinymce-editor/). NOTA: Tot i que l'article és antic, el hook és senzill i funciona. Provat amb chrome. 

NOTA: el plugin Preserved HTML Editor Markup és obsolet (més de 2 anys sense manteniment)

**Comment by jmeler** [comment]
De moment, afegim només aquest hook amb 

$ext = 'embed[flashvars]';

**Comment by toniginard** [comment]
Fixed in https://github.com/projectestac/wordpress-mu-common/commit/3296c2fb724a4b4fadf10f2e0b1145bf265a787f
