### ISSUE TITLE
Enllaços predeterminats trencats a la pàgina de Documents

### ISSUE THREAD

**Issue by jordifalip** [projectestac/agora_nodes#436]
Bon dia.

La pàgina de Documents de qualsevol lloc web de NODES amb els documents predeterminats està desactualitzada. Alguns dels documents enllaçen amb una web no existent des de que la XTEC va canviar de domini.

Documents:
- Els 2 documents d'autorització d'imatge
- Els 2 documents d'autorització d'ús de serveis i recursos digitals a l’aula

Gràcies,
Jordi

**Comment by sarjona** [comment]
Hola Jordi!
Gràcies per l'avís. Hem demanat als responsables de la XTEC els enllaços dels documents nous per actualitzar els enllaços que comentes.
Us mantindrem informats.
Una abraçada,
Sara

**Comment by jordifalip** [comment]
Gràcies Sara!

**Comment by jmeler** [comment]
S'han actualitzat els enllaços als 4 documents. Ara apunten als nous documents.
