### ISSUE TITLE
El contorn de les taules no es pot amagar

### ISSUE THREAD

**Issue by jordifalip** [projectestac/agora_nodes#438]
Bona nit.

Tinc un problema amb el NODES. No puc amagar de cap manera el contorn de les taules.

Si des de l'editor poses el valor "0" al camp "Contorn", en realitat no estàs modificant res, ja que el contorn segueix mostrant-se.

![taula](https://cloud.githubusercontent.com/assets/20835934/17459292/105ad22e-5c32-11e6-9a7e-a98b379dd091.PNG)

Si li poses que el contorn sigui de color blanc (com el fons), segueix mostrant-se en el mateix color.

![taula2](https://cloud.githubusercontent.com/assets/20835934/17459295/254a31fc-5c32-11e6-9bc9-28077c446727.PNG)

[Aprofitant aquesta última captura comento un altre problema "estètic". Com veieu, el color de fons de la taula també està marcat com a blanc total, tot i que el resultat és veure la taula en gris i blanc.]

Resultat: impossible treure el contorn...

![taula3](https://cloud.githubusercontent.com/assets/20835934/17459299/3c839c32-5c32-11e6-96c2-fef69f7c9c4d.PNG)

Entenc que això és un problema, però hi ha alguna altra forma de treure'l?

Gràcies i bon estiu.

Jordi

**Comment by frncesc** [comment]
En realitat el contorn que veus no és el de la taula, sinó el de les cel·les que en formen part.

Per treure'l, selecciona totes les cel·les de la taula, ves a __Taula | Cel·les | Propietats de les cel·les__ i, a la pestanya __Avançat__ posa-hi:

`border:0;`

Amb això hauria de quedar la taula neta, sense els contorns de les cel·les.
