### ISSUE TITLE
Eines: Exportador d'horaris i gestio d'esdeveniments

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#442]
Afegir 2 metaboxes a **Tauler** -> **Eines disponibles** amb els següents textos: 

**Metabox 1:** 

**Títol:** Exportador d'horaris
**Text:** 
A partir d'un full de càlcul de Google, aquesta eina permet exportar a format web els horaris de cada grup, professor, assignatura o aula. El codi generat és pot inserir fàcilment a qualsevol pàgina de Nodes editant la pàgina i enganxant el codi a la pestanya Text.

[Enllaç al exportador d'horaris](http://blocs.xtec.cat/coordinaciotac/2015/09/16/exportador-dhoraris-web/)

Imatge (pendent)

Desenvolupat per: Felix Tejero 

**Metabox 2:** 

**Títol:** Gestor d'esdeveniments
**Text:** 
A partir d'un full de càlcul de Google, aquesta eina permet actualitzar els calendaris del curs amb un sol clic. Tant mateix, si afegiu nous esdeveniments als calendaris, s'incorporen al full de càlcul. 

[Enllaç al gestor d'esdeveniments](http://blocs.xtec.cat/coordinaciotac/2015/09/21/gestio-dels-esdeveniments-del-curs/)

Imatge (pendent)

Desenvolupat per: Pepi Garrote

**Comment by jmeler** [comment]
Afegir un metabox nou a Eines disponibles amb el títol: 

**Exportar horaris al web**

**Comment by sarjona** [comment]
![eines_amagades](https://cloud.githubusercontent.com/assets/900389/18511709/97aac600-7a85-11e6-8159-0e5fc43e4556.png)

El @jmeler ha demanat amagar també les caixes d'eines "Convertidor de categories i etiquetes" i "Eines del BuddyPress"

**Comment by sarjona** [comment]
Integrat al commit https://github.com/projectestac/agora_nodes/commit/9df6c6dead7e766d7db59480f5b0e5432bf811eb
