### ISSUE TITLE
Estils simple Calendar 

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#443]
Adaptar els estils del calendari del nou simple calendar al estil de nodes (sense vores). Pendre com referència el actual estil del calendari. 
![seleccio_999 368](https://cloud.githubusercontent.com/assets/5380649/18266241/18314fc8-741a-11e6-82f4-3e70c7fe2d5c.png)

**Comment by toniginard** [comment]
Fixed in commit https://github.com/projectestac/agora_nodes/commit/ae423d7743147dbf98eeb0869fb1eb4363a24a7b

**Comment by toniginard** [comment]
New commit for this change: https://github.com/projectestac/agora_nodes/commit/c1b990862f48db2357acebbd3c4d7f6a8f1902a5
