### ISSUE TITLE
Incorporació de complement Gallery Custom Links 

### ISSUE THREAD

**Issue by jordifalip** [projectestac/agora_nodes#445]
Bona tarda, equip d'Àgora.

Estem encantats amb el nou web nodes.

Però trobo a faltar una funció, i es que en una galeria les imatges funcionin com a enllaços a altres pàgines web.

He fet una cerca per Internet i he vist que el plugin més addient s'anomena WP Gallery Custom Links (https://wordpress.org/plugins/wp-gallery-custom-links/).

Es podria valorar la seva incorporació en la futura actualizació? Ens aniria molt bé!!

Moltes gràcies per tot.

Salutacions!

**Comment by comunicaciotorroja** [comment]
Bona nit.

A nosaltres també ens aniria bé. Tenim una pàgina mare amb una galeria i seria interessant que es pogués redireccionar a una altra pàgina en prémer una de les imatges.

Per si li voleu donar una ullada: http://agora.xtec.cat/iesantonitorroja/departaments/

Moltes gràcies.

**Comment by jmeler** [comment]
Tot i que els autors del plugin només han fet un, són una empresa que viu de WordPress. El plugin té un bon nombre de descàrregues, un bon nombre de valoracions positives i poca activitat al fòrum de support. No és un plugin complex de desenvolupar ni mantenir. Inclou fitxers d'idiomes i esta preparat per shortcodes. Dos detalls de qualitat. Endavant amb la seva instal·lació.

**Comment by sarjona** [comment]
@jmeler Aplica només a Nodes o també a XTECBlocs?

**Comment by jmeler** [comment]
@sarjona sí, també per XTECBlocs.

**Comment by sarjona** [comment]
Dimarts es va acordar tancar aquesta petició perquè l'extensió no està suportada.
