### ISSUE TITLE
Possibilitat de fer reserves usuaris no autenticats

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#454]
Ens arriba aquesta petició d'un SE al fòrum: http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=85326#p326470

**Comment by jmeler** [comment]
Els nodes del servei educatiu teniu LDAP xtec activat, de manera que qualsevol docent amb correu xtec, pot entrar automàticament en el vostre Nodes. No cal donar d'alta cap usuari perquè poden entrar directament. Una vegada autenticats, podran fer servir el formulari de reserves sense problemes.

**Comment by monicagrau** [comment]
Els usuaris que accedeixin amb LDAP per defecte tenen rol col·laborador i aquests no poden fer reserves. S'hauria de canviar el rol per defecte en accedir a "Professor" perquè els funcioni. Cal tenir en compte que les reserves amb rol "Profesor" no queden pendents de validació.
