### ISSUE TITLE
No es mostren els ginys a la portada

### ISSUE THREAD

**Issue by jomenci28** [projectestac/agora_nodes#460]
Hola, bones

porto un temps ja amb el Nodes i n'estic molt content amb els seus resultats. En varem parlar al maig i em vàreu guiar. Gràcies.

tinc dues inquietuds que des del principi no he pogut resoldre, i és que, quan configuro una pàgina de portada (inici) i una d'entrades, des de l'apartat opcions -> lectura, (és la millor opció per mi), aleshores no es mostren els ginys a la barra dreta, ni es esquerra, ni configurant-ho des de les opcions de personalització del tema (reactor NODES) -> Ginys, ni configurant-ho des del panell -> aparença -> ginys.

No sé com fer-ho, potser no tinc la pg. d'inici ben posada als ginys? com l'hi afegeixo?
si em podeu guiar en què estic fent malament, us ho agraïria

moltes gràcies!

Josep

**Comment by jmeler** [comment]
Aquest tipus de consulta s'han de fer al[ fòrum de suport](http://agora.xtec.cat/moodle/moodle/mod/forum/view.php?id=1721).
