### ISSUE TITLE
Petit bug del giny "Comptador de visites"

### ISSUE THREAD

**Issue by comunicaciotorroja** [projectestac/agora_nodes#462]
Hola,

si consulteu la pàgina principal del nostre Nodes, http://agora.xtec.cat/iesantonitorroja/, i aneu al comptador situat al peu de pàgina, veureu que en prémer a sobre d'aquest redirigeix al web del Museu de Cervera. Tenim un giny a la barra dreta que és el que "oficialment" porta al web del Museu, però en cap moment li hem dit al comptador que porti en aquest web.

Creieu que es tracta d'un bug de Nodes?

Gràcies!

Marc

**Comment by sarjona** [comment]
Hola Marc!

Aquest tipus de missatges és preferible que ens els feu arribar a través del fòrum de suport del projecte Àgora-Nodes: http://agora.xtec.cat/moodle/moodle/mod/forum/view.php?id=1721 . En cas que sigui una incidència, procedirem a donar-ho d'alta a aquest espai (on només tenim les incidències). Així ens resultarà més senzill fer el seguiment i diferenciar les incidències dels dubtes... Pots enviar a l'espai de suport aquests missatges?

Una abraçada i gràcies per la comprensió! :-)

Sara
