### ISSUE TITLE
Manca de traduccions en algunes pàgines

### ISSUE THREAD

**Issue by comunicaciotorroja** [projectestac/agora_nodes#465]
Hola,

sento tantes incidències de cop, però penso que és millor posar-les per separat i no totes en una.

En el tema de Nodes manquen algunes traduccions.

1.- Quan una pàgina no existeix, el quadre de cerca i el botó per cercar no estan traduïts (exemple: https://agora.xtec.cat/formacio/secundaria/aquestapaginanoexisteix)

2.- Els títols d'alguns ginys (és possible que siguin els títols oficials dels complements fets per tercers).

![traduccionsginys](https://cloud.githubusercontent.com/assets/22156324/19212518/2a8363d0-8d53-11e6-9dfe-faa697b29c3b.PNG)
1. Algunes frases de la pantalla "Configuració general" del complement Carrousels.
2. Les opcions de personalització de Buddypress Emails:

![buddypresstranslations1](https://cloud.githubusercontent.com/assets/22156324/19212563/f2ab82ac-8d53-11e6-9137-89fb3e19ab01.PNG)
![buddypresstranslations2](https://cloud.githubusercontent.com/assets/22156324/19212562/f2aae7d4-8d53-11e6-8384-3f6ff1599894.PNG)

Gràcies,
Marc

**Comment by sarjona** [comment]
Desplegat a la versió 17.02.13
