### ISSUE TITLE
Errada del plugin Email Subscribers

### ISSUE THREAD

**Issue by comunicaciotorroja** [projectestac/agora_nodes#466]
Hola novament,

hem detectat un problema en el plugin Email Subscribers, els firma l'Institut L'Arany.

> Si no esteu interessats en rebre correus des de Institut L'Arany feu clic aquí per donar-vos de baixa.

El nostre web és http://agora.xtec.cat/iesantonitorroja.

Hem vist al fòurm del web Àgora que no som l'únic centre que té aquest problema, així que ho escric aquí per si es tracta d'una errada general de Nodes.

Si ens ho poguéssiu arreglar, n'estariem molt agraïts.

Moltes gràcies.

Atentament,
Marc

**Comment by sarjona** [comment]
Hola Marc!

Aquest tipus de missatges és preferible que ens els feu arribar a través del fòrum de suport del projecte Àgora-Nodes: http://agora.xtec.cat/moodle/moodle/mod/forum/view.php?id=1721 . En cas que sigui una incidència, procedirem a donar-ho d'alta a aquest espai (on només tenim les incidències). Així ens resultarà més senzill fer el seguiment i diferenciar les incidències dels dubtes... Pots enviar a l'espai de suport aquests missatges?

Una abraçada i gràcies per la comprensió! :-)

Sara
