### ISSUE TITLE
Suggeriment: Afegir extensió per generar formularis

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#467]
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=90907

**Comment by jmeler** [comment]
Els formularis de Google són prou funcionals per la majoria de necessitats. Mantenir Nodes amb els menor número de plugins és un dels nostres objectius per millorar el manteniment i la seguretat de la plataforma. 
Per una altra banda, part dels formularis relacionats amb la reserva d'aules i recursos es poden implementar amb el plugin **Reserves** dissenyat específicament per a la plataforma Nodes.
