### ISSUE TITLE
Amagar i renombrar elements del constructor de menús

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#480]
Configurar "Opcions de pantalla" del constructor de menús perque, per defecte, només es mostrin els següents elements: 

![seleccio_999 413](https://cloud.githubusercontent.com/assets/5380649/19952185/a54126ba-a163-11e6-91b4-fb43034d1e60.png)

Afegiré properament una proposta de canvis d'alguns elements perquè tenen el mateix nom (4 es diuen "Etiquetes", tenim 2 "Categories" etc.)

**Comment by jmeler** [comment]
Eliminació o ocultació del següents elements del menú relacionats amb el **BP-Docs**. Lo ideal és desactivar el hook del BP-Docs que crea aquests elements al constructor de menús:

- Eliminar element **Etiquetes (bp_docs_access open)**
- Eliminar element **Etiquetes (bp_docs_folder_in_group open)**
- Eliminar element **Etiquetes (bp_docs_folder_in_user)**

**Comment by jmeler** [comment]
Eliminació o ocultació dels següents elements. Lo ideal és desactivar el hook que afegeixen aquests elements al constructor. Però valorar impacte en el manteniment al actualitzar.
- Nodes convidats
- Convidats
- Format

**Comment by toniginard** [comment]
Resolt en el commit https://github.com/projectestac/agora_nodes/commit/576aeb66580b2ae953427468f307a633b9da49b6
