### ISSUE TITLE
Evitar solapament desplegable

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#483]
Es produeix un solapament entre la fletxeta del desplegable per definir una nova visibilitat i l'enllaç "Esborra", de manera que al intentar definir una nova entrada a visibilitat, s'esborra l'entrada. És al fer clic a sobre de la fletxeta del desplegable.

**Comment by toniginard** [comment]
Fixed in commit https://github.com/projectestac/wordpress-widget-visibility-without-jetpack/commit/9a3e69e4fc2d2279b40bef0ffca2bc8da19715c0
