### ISSUE TITLE
Desplegar elements de simple calendar en moure el ratolí

### ISSUE THREAD

**Issue by frncesc** [projectestac/agora_nodes#485]
A partir d'algunes demandes al fòrum d'Àgora ([1](http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=90328#p331993), [2](http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=90407&parent=332392)) he preparat un petit script que fa que al cap de mig segon de deixar el ratolí quiet damunt una casella del calendari es simuli un clic de ratolí damunt seu, obrint-se així la finestra amb el detall dels esdeveniments.

Us passo el codi per si considereu oportú afegir-lo:

```
// Execute on document ready
jQuery(
  // Handle only events originated on '.simcal-event-dots' (cells with dots)
  jQuery('.simcal-calendar').on('mouseenter', '.simcal-events-dots', function(){

    // Save the cell that originated the mouse event (assigned to 'this' by jQuery)
    // for future reference
    var that = this;

    // Set a timeout handler that will trigger a 'click' on the cell
    var timeoutId = setTimeout(function(){    
      jQuery(that).removeData('simcalTimeoutId');
      jQuery(that).trigger('click');
    }, 500);

    // Save 'timeoutId' for future reference
    jQuery(this).data('simcalTimeoutId', timeoutId);

  }).on('mouseleave', '.simcal-events-dots', function(){
    // Clear timeout and remove reference
    var timeoutId = jQuery(this).data('simcalTimeoutId');
    if(timeoutId) {
      clearTimeout(timeoutId);
      jQuery(this).removeData('simcalTimeoutId');
    }
  })
);
```

**Comment by sarjona** [comment]
S'ha incorporat el pegat al PR https://github.com/projectestac/wordpress-gce/pull/7 (està pendent integració).

**Comment by sarjona** [comment]
Incorporat al commit https://github.com/projectestac/wordpress-gce/commit/d0252bce5dd3ff554f587f9d23f5bfe073cafaac
