### ISSUE TITLE
Permetre pujar fitxers SWF als Nodes?

### ISSUE THREAD

**Issue by monicagrau** [projectestac/agora_nodes#500]
Des del fòrum ens demanen poder pujar/visualitzar fitxers SWF als Nodes.
http://agora.xtec.cat/moodle/moodle/mod/forum/discuss.php?d=93787

**Comment by jmeler** [comment]
No es farà. La tecnologia flash desapareixerà en breu i els navegadors deixaran de donar suport de la mateixa manera que els dispositius mòbils ja no permeten la visualització de molt contingut flash.
