### ISSUE TITLE
Al publicar reserva periòdica, apareix llista d'articles en lloc de la llista de reserves

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#516]
És bastant desconcertant perquè sembla que la reserva no s'ha fet. Tampoc mostra el missatge de ok (Reserva publicada). Només passa amb la reserva "múltiple" o periòdica. 

El comportament hauria de ser semblant a la reserva simple.

**Comment by monicagrau** [comment]
Xavi, pots tornar-ho a provar? a mi no m'ha passat, potser encara s'estava actualtizant...

**Comment by jmeler** [comment]
sí, funciona ok. Esborro issue.
