### ISSUE TITLE
Algunes accions sobre els nodes no funcionen

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#521]
El formulari de petició d'entrada apareix però al fer clic, no passa de pantalla. 

Aprofitar la correcció per canviar el literal del botó "Sol·licituds" per "Uneix-te al node" i el literal de la pestanya "Sol·licituds d'amistad" per "Sol·licitud" 

![seleccio_999 454](https://cloud.githubusercontent.com/assets/5380649/22287361/e3f94862-e2f2-11e6-8da2-9b0bd59223a5.png)

**Comment by jmeler** [comment]
- No es pot esborrar un node creat
- No es pot actualitzar un node (paràmetres, subscripció de correu, etc)

Sí que es pot crear un node.

**Comment by jmeler** [comment]
Apunta a tema rutas

![seleccio_999 455](https://cloud.githubusercontent.com/assets/5380649/22288780/b8de537e-e2f8-11e6-9db7-019f812c66df.png)

**Comment by sarjona** [comment]
Resolta al commit https://github.com/projectestac/agora/commit/acf9b96eedb93f7db7c9f73b62436b13e31f8b5b
