### ISSUE TITLE
Autenticació per google d'usuaris externs (no xtec)

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#546]
Tot i que l'usuari estigui a la llista blanca, el sistema **no fa el lligam** entre el compte Google i el nou usuari Nodes. Sí que valida amb Google, però no crea l'usuari a Nodes ni fa el lligam. S'ha provat amb un compte estandar gmail.

**Comment by jmeler** [comment]
Els usuaris gmail no xtec no poden validar tot i que estiguin a la llista blanca. Fins i tot usuaris ja donats d'alta i que s'havien validat prèviament.

**Comment by sarjona** [comment]
També convindria revisar en algun moment la traducció perquè el mòdul incorpora una pantalla que es mostra en anglès (s'adjunta captura de pantalla).
![wsl_angles](https://cloud.githubusercontent.com/assets/900389/26343514/8fe199da-3f9c-11e7-934d-bdd03d0417ff.png)

**Comment by sarjona** [comment]
Correspon a la petició 1051-2017-0006 de l'AGIN

**Comment by toniginard** [comment]
Es va iniciar una branca per fer que no surti la pantalla de la captura anterior, de manera que el sistema prengui la decisió de manera automàtica i no pregunti a l'usuari. La tasca va quedar pendent de revisar les implicacions que té aquest canvi. Cal tenir en compte que la pantalla no apareix sempre i cal identificar les casuístiques.

https://github.com/projectestac/wordpress-social-login/commits/WIP-Not-Show-Intermediate-Page-Oauth-Login
