### ISSUE TITLE
No carrega la pàgina en accedir a un fil del fòrum

### ISSUE THREAD

**Issue by acoll23** [projectestac/agora_nodes#573]
En accedir a un fil del fòrum no es visualitza cap missatge, ni la capçalera del web, ni els botons dels nodes. No finalitza la càrrega de la pàgina. Pot estar relacionat amb l'extensió TOC+ 

https://agora.xtec.cat/nodes/els-nodes/fotografia/forum/topic/prova-de-fotos/

![image](https://user-images.githubusercontent.com/8777430/28660923-3708c134-72b5-11e7-8835-baa4d06f214d.png)

**Comment by jmeler** [comment]
Depén del contingut. Aquest fil sí que el carrega bé: 
https://agora.xtec.cat/nodes/els-nodes/col%C2%B7laboracio-escola-illa/forum/topic/projecte-nodes/

**Comment by acoll23** [comment]
No depèn del contingut, depèn del perfil de l'usuari. A un usuari "normal", sigui membre, moderador o administrador no li funciona correctament. Ara bé, amb l'usuari xtecadmin tot funciona correctament. L'usuari que ha creat el fil del fòrum tampoc no el pot veure.

**Urgent per EduHack**:
https://projectes.xtec.cat/eduhack/nodes/coordinacio-edu-hack/forum/topic/gral-iniciem-el-forum-proposta-dinstruccions-per-participar-en-el-forum/

**Comment by slva** [comment]
S'ha detectat que s'exhaureix el limit de crides aniuades de funcions.
S'ha solucionat desinstal·lant un modul que no era necessari a producció
