### ISSUE TITLE
Modificacions al giny "Enllaços Educatius"

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#574]
- Treure la icona/opció **Intraweb.**
- Afegir la icona/opció de **Esfer@**: El text és **Esfer@**, l'enllaç és https://bfgh.aplicacions.ensenyament.gencat.cat/bfgh/ i la icona 
![esfera](https://user-images.githubusercontent.com/5380649/28928951-fb8de584-786e-11e7-99fe-637d227fea2b.png)
-Afegir l'opció **eValisa**: el text és **eValisa**, l'enllaç és https://idpeacat.gencat.cat/group/1/valisa i la icona 
![evalisa](https://user-images.githubusercontent.com/5380649/28929563-8fe59492-7870-11e7-8363-96695f8a967b.png)
-Afegir l'opció **IOC**: el text és **Institut Obert de Catalunya**, l'enllaç és http://ioc.xtec.cat/ i la icona és: 
![ioc](https://user-images.githubusercontent.com/5380649/28929835-548d5564-7871-11e7-9365-7e9f4f4fa9a7.png)
-Afegir l'opció **Sinapsi**: el text és **Sinapsi**, l'enllaç és http://sinapsi.xtec.cat i la icona és
![sinapsi](https://user-images.githubusercontent.com/5380649/28930901-a61038f4-7874-11e7-8955-2d86c4aa4c7e.png)

NOTA: Aquesta issue és una agrupació de les issues #221, #419, #544

**Comment by slva** [comment]
@acoll23 tanco l'issue tal com hem parlat a la reunió per tal d'ajustar-nos al workflow comentat.
