### ISSUE TITLE
Amagar l'opció CSS adicionals del Personalitzador 

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#575]
El disseny a Nodes té un component corporatiu important. Tot i que hi ha elements personalitzables, es vol mantenir una coherència entre totes les webs de centre i la personalització directa d'estils no es pot permetre, o com a mínim, d'una manera tan directa. 

Només visible per el **superadministrador**, no l'administrador. 

![image](https://user-images.githubusercontent.com/5380649/28932205-f11ce94c-7878-11e7-8ee1-c06eaa33d5a5.png)

**Comment by slva** [comment]
Segons ultimes reunions s'acorda mantenir la opció disponible.
