### ISSUE TITLE
Traducció Sol·licituds

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#576]
El botó que serveix per demanar l'entrada en un node, està traduït per **Sol·licituds**. El terme és confús ja que sembla que sigui una llista de persones que han demanat l'entrada. També apareix una pestanya que té el mateix objectiu amb el títol "Sol·licituds d'amistad" 

Canviar **Sol·licituds** i **Sol·licituds d'amistad** per **Vull ser membre**.  
 
![image](https://user-images.githubusercontent.com/5380649/29062127-bd17155e-7c20-11e7-9528-2c1d4ccd0b92.png)

**Comment by slva** [comment]
@acoll23 tanco l'issue tal com hem parlat a la reunió per tal d'ajustar-nos al workflow comentat.
