### ISSUE TITLE
Capçalera CEB

### ISSUE THREAD

**Issue by Juanjido** [projectestac/agora_nodes#624]
Bon dia!
Tinc un problema amb la capçalera dels SE de Barcelona Comarques, que apareix aquesta referència del Consorci i no acabo de trobar la manera de treure-la, si és que puc, començo a pensar que no, hauria de sortir el logo del Departament, com a la resta de SE:

![SE Barcelona Comarques_LI](https://user-images.githubusercontent.com/118533339/202710205-0b140458-ac75-42dd-9879-79f8cee5a8e2.jpg)

Moltes gràcies,
Juan Jiménez

**Comment by frncesc** [comment]
Hauries de posar una incidència al SAU demanant que ho canviïn.

Indica'ls que, tot i trobar-se a Barcelona, no és la seu d'un centre ni d'un servei educatiu.
