### ISSUE TITLE
L'etiqueta 'llegeix més' dins d'un article no fa cap efecte

### ISSUE THREAD

**Issue by joanjoc** [projectestac/agora_nodes#67]
Si al editar una entrada del wordpress s'afegeix l'etiqueta 'llegeix més', dins el codi html de l'entrada queda insertada l'etiqueta , però al visualitzar aquesta entrada des de la portada no es veu cap enllaç convidant al lector a continuar llegint la resta de l'entrada.

**Comment by sarjona** [comment]
Sembla que ara ja funciona.
