### ISSUE TITLE
Afegir sistema de registre (accessos, accions)

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#87]
Afegir un sistema de registre:
- accessos
- accions principals (edició d'articles, gestió d'usuaris etc...)

Estudiar si el sistema ha de funcionar sobre fitxers o sobre base de dades. 
Mecanismes de neteja

**Comment by sarjona** [comment]
Funcionalitats implementades al connector xtec-stats.

@jmeler es pot tancar la petició o queda pendent alguna cosa?
