### ISSUE TITLE
Giny Grup-classe: títol d'Enllaços 

### ISSUE THREAD

**Issue by jmeler** [projectestac/agora_nodes#89]
Si no hi ha enllaços seleccionats, hauria de no mostrar el títol

**Comment by frncesc** [comment]
Potser hauríem de fer extensiu el criteri a tots els camps i seccions: si el camp es deixa en blanc no es mostra, i si una secció té tots els camps en blanc, tampoc. Per exemple, un tutor pot no tenir horari de visites fix (l'habitual a primària és que sigui així), o pot ser que una classe encara no tingui agenda.
